import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs/promises';
test.setTimeout(30000);

const state = (page: Page) => page.evaluate(() => (window as any).__MIU_DEBUG.getState());
const act = (page: Page, action: unknown) => page.evaluate(action => (window as any).__MIU_DEBUG.dispatch(action), action);
async function start(page: Page) {
 await page.goto('/');
 await page.getByRole('button', { name: 'Bắt đầu chăm tiệm' }).click();
 await expect(page.locator('.cafe-scene canvas')).toHaveCount(1);
}
async function closePanel(page: Page) { await page.getByRole('button', { name: 'Đóng bảng', exact: true }).last().click(); }
async function fixture(page: Page, incident = false) {
 return page.evaluate(async ({ incident }) => {
  const engineSource = '/src/domain/engine.ts'; const engine = await import(engineSource);
  let fresh = engine.createGame({ seed: 117243, dayDuration: 660 });
  fresh.xp = 80; fresh.level = 2; fresh.tutorial = 1;
  fresh = engine.reduceGame(fresh, { type: 'OPEN' });
  fresh.nextCustomerAt = 1_000_000; fresh.nextIncidentAt = 1_000_000;
  fresh = engine.reduceGame(fresh, { type: 'ORDER', customerId: 'linh', recipeId: 'matcha-latte', kind: 'table' });
  if (incident) {
   const coordinatorSource = '/src/domain/events.ts'; const coordinator = await import(coordinatorSource);
   const generated = coordinator.triggerIncident(fresh, 'spill');
   if (!generated) throw new Error('Eligible spill fixture was not generated by coordinator');
  }
  (window as any).__MIU_DEBUG.replace(fresh);
  return (window as any).__MIU_DEBUG.getState();
 }, { incident });
}
async function step(page: Page, seconds: number) {
 await page.evaluate(seconds => {
  const debug = (window as any).__MIU_DEBUG;
  debug.dispatch({ type: 'PAUSE', paused: false });
  while (seconds > 0) { const n = Math.min(seconds, 60); debug.dispatch({ type: 'STEP', seconds: n }); seconds -= n; }
  debug.dispatch({ type: 'PAUSE', paused: true });
 }, seconds);
}
async function saved(page: Page) {
 return page.evaluate(async () => { const source = '/src/persistence.ts'; const persistence = await import(source); return persistence.loadGame(); });
}
function workerCard(page: Page) { return page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Lan', exact: true }) }); }
async function hire(page: Page) {
 await page.getByRole('button', { name: 'Nhân viên', exact: true }).click();
 await workerCard(page).getByRole('button', { name: 'Tuyển Lan', exact: true }).click();
 const snapshot = await state(page);
 expect(snapshot.staff.find((worker: any) => worker.id === 'lan').hired).toBe(true);
 expect(snapshot.transactions.filter((entry: any) => entry.id === 'hire:lan')).toHaveLength(1);
}

test('Tuyển Lan qua giao diện: tác vụ pha tự động chạy đủ thời gian và chỉ dùng kho một lần', async ({ page }, testInfo) => {
 await start(page); const initial = await fixture(page); const orderId = initial.orders[0].id;
 await hire(page); await step(page, 1);
 let current = await state(page); const task = current.tasks.find((task: any) => task.targetId === orderId);
 expect(task.status).toBe('working'); expect(current.orders[0].worker).toBe('lan');
 expect(current.orders[0].status).toBe('making'); expect(current.cash).toBe(835000);
 const inventoryAfterStart = current.inventory.map((batch: any) => [batch.id, batch.quantity]);
 const cost = current.orders[0].draft.cost;
 expect(current.transactions.filter((entry: any) => entry.id === `consume:${orderId}`)).toHaveLength(1);
 await expect(workerCard(page)).toContainText(`drink · ${task.remaining}s còn lại`);
 await step(page, task.remaining - 1); current = await state(page);
 expect(current.orders[0].status).toBe('making');
 expect(current.tasks.find((entry: any) => entry.id === task.id).remaining).toBe(1);
 await step(page, 1); current = await state(page);
 expect(current.orders[0].status).toBe('ready'); expect(current.orders[0].score.total).toBeGreaterThan(0);
 expect(current.tasks.find((entry: any) => entry.id === task.id).status).toBe('done');
 expect(current.staff.find((worker: any) => worker.id === 'lan').experience).toBe(1);
 expect(current.inventory.map((batch: any) => [batch.id, batch.quantity])).toEqual(inventoryAfterStart);
 expect(current.transactions.find((entry: any) => entry.id === `consume:${orderId}`).cogs).toBe(cost);
 await page.screenshot({ path: `screenshots/staff-work-${testInfo.project.name}.png`, fullPage: true });
 await closePanel(page); await page.locator('.order-card').filter({ hasText: 'Linh' }).getByRole('button').click();
 await page.getByRole('button', { name: 'Giao đúng đơn & thu tiền' }).click();
 current = await state(page); expect(current.orders[0].paid).toBe(true);
 expect(current.transactions.filter((entry: any) => entry.id === `sale:${orderId}`)).toHaveLength(1);
 await act(page, { type: 'SERVE', orderId }); await step(page, 10);
 current = await state(page);
 expect(current.transactions.filter((entry: any) => entry.id === `consume:${orderId}`)).toHaveLength(1);
 expect(current.transactions.filter((entry: any) => entry.id === `sale:${orderId}`)).toHaveLength(1);
});

test('Chấm dứt giữa ca có xác nhận: bàn giao ly, chủ tiệm tiếp quản và không phát sinh lương mới', async ({ page }, testInfo) => {
 await start(page); const initial = await fixture(page); const orderId = initial.orders[0].id;
 await hire(page); await step(page, 3);
 const working = await state(page); const taskId = working.staff.find((worker: any) => worker.id === 'lan').taskId;
 const used = working.inventory.map((batch: any) => [batch.id, batch.quantity]);
 await workerCard(page).locator('summary').click();
 await workerCard(page).getByRole('button', { name: 'Chấm dứt hợp đồng', exact: true }).click();
 expect((await state(page)).staff.find((worker: any) => worker.id === 'lan').hired).toBe(true);
 await expect(page.getByRole('button', { name: 'Xác nhận chấm dứt & thanh toán' })).toBeVisible();
 await page.screenshot({ path: `screenshots/staff-handoff-${testInfo.project.name}.png`, fullPage: true });
 await page.getByRole('button', { name: 'Xác nhận chấm dứt & thanh toán' }).click();
 let current = await state(page); const former = current.staff.find((worker: any) => worker.id === 'lan');
 expect(former.former).toBe(true); expect(former.hired).toBe(false); expect(former.onShift).toBe(false);
 expect(current.tasks.find((entry: any) => entry.id === taskId).status).toBe('handed-over');
 expect(current.orders[0].worker).toBeUndefined(); expect(current.orders[0].draft.worker).toBeUndefined();
 expect(current.orders[0].status).toBe('making');
 expect(current.inventory.map((batch: any) => [batch.id, batch.quantity])).toEqual(used);
 expect(current.transactions.filter((entry: any) => entry.id === 'salary-fire:lan:1')).toHaveLength(1);
 const settledSalary = current.transactions.filter((entry: any) => entry.category === 'salary');
 const secondsWorked = former.secondsWorked;
 await closePanel(page); await page.getByRole('button', { name: 'Tiếp tục pha', exact: true }).click();
 await page.getByRole('button', { name: 'Pha nhanh · kỹ thuật 40/100' }).click();
 await page.getByRole('button', { name: 'Giao đúng đơn & thu tiền' }).click();
 await step(page, 60); current = await state(page);
 expect(current.staff.find((worker: any) => worker.id === 'lan').secondsWorked).toBe(secondsWorked);
 expect(current.tasks.filter((entry: any) => entry.workerId === 'lan')).toHaveLength(1);
 expect(current.transactions.filter((entry: any) => entry.id === `consume:${orderId}`)).toHaveLength(1);
 expect(current.orders[0].paid).toBe(true);
 await page.getByRole('button', { name: 'Đóng cửa', exact: true }).click();
 current = await state(page); expect(current.phase).toBe('after');
 expect(current.transactions.filter((entry: any) => entry.category === 'salary')).toEqual(settledSalary);
 expect(current.transactions.some((entry: any) => entry.id === 'salary:lan:1')).toBe(false);
 await page.getByRole('button', { name: 'Ngày tiếp theo', exact: true }).click(); await step(page, 5);
 current = await state(page); expect(current.staff.find((worker: any) => worker.id === 'lan').former).toBe(true);
 expect(current.transactions.filter((entry: any) => entry.category === 'salary')).toEqual(settledSalary);
});

test('Sự cố từ coordinator: kiểm chứng dữ kiện, xử lý có thời gian, lưu tải không trừ chi phí lần nữa', async ({ page }, testInfo) => {
 await start(page); const initial = await fixture(page, true); const incident = initial.incidents[0];
 expect(incident.participants).toContain(initial.orders[0].customerId);
 await page.getByRole('button', { name: /^Đời sống tiệm/ }).click();
 await expect(page.getByRole('heading', { name: incident.title, exact: true })).toBeVisible();
 for (let index = 0; index < incident.evidence.length; index++) await page.getByRole('button', { name: 'Kiểm tra', exact: true }).first().click();
 let current = await state(page); expect(current.incidents[0].evidence.every((entry: any) => entry.checked)).toBe(true);
 expect(current.incidents[0].cause).toBe('accident');
 const option = page.locator('.panel').filter({ has: page.getByRole('heading', { name: 'Đặt biển và lau', exact: true }) });
 await option.getByRole('button', { name: 'Chọn cách xử lý', exact: true }).click();
 current = await state(page); expect(current.incidents[0].stage).toBe('investigating');
 expect(current.cash).toBe(initial.cash - 3000);
 await expect(page.getByText(/Đang xử lý · 12s còn lại/)).toBeVisible();
 await step(page, 11); expect((await state(page)).incidents[0].stage).toBe('investigating');
 await step(page, 1); current = await state(page);
 expect(current.incidents[0].stage).toBe('resolved'); expect(current.flags.floorSafe).toBe(true);
 expect(current.transactions.filter((entry: any) => entry.id === `resolve-cost:${incident.id}`)).toHaveLength(1);
 await page.screenshot({ path: `screenshots/incident-${testInfo.project.name}.png`, fullPage: true });
 await expect.poll(async () => (await saved(page))?.incidents[0]?.stage).toBe('resolved');
 const cash = current.cash; await page.reload(); await page.waitForFunction(() => !!(window as any).__MIU_DEBUG);
 await expect.poll(async () => (await state(page)).incidents[0]?.stage).toBe('resolved');
 await act(page, { type: 'RESOLVE', incidentId: incident.id, choiceId: 'clean' }); await step(page, 20);
 current = await state(page); expect(current.cash).toBe(cash);
 expect(current.transactions.filter((entry: any) => entry.id === `resolve-cost:${incident.id}`)).toHaveLength(1);
 expect(current.incidents.filter((entry: any) => entry.id === incident.id)).toHaveLength(1);
});

test('Mười món, công thức sencha riêng và mọi tab xưởng vẽ có tài nguyên cục bộ tải được', async ({ page }, testInfo) => {
 const errors: string[] = [], brokenAssets: string[] = [];
 page.on('pageerror', error => errors.push(error.message));
 page.on('response', response => { if (response.status() >= 400 && response.url().includes('/assets/')) brokenAssets.push(response.url()); });
 await start(page); await fixture(page);
 await page.getByRole('button', { name: 'Thực đơn', exact: true }).click();
 await expect(page.locator('.product-art')).toHaveCount(10);
 await page.getByRole('button', { name: 'Tạo công thức', exact: true }).click();
 await page.getByLabel('Tên món', { exact: true }).fill('Mây sencha của tiệm');
 await page.getByRole('combobox', { name: 'Trà', exact: true }).selectOption('sencha');
 await page.getByRole('button', { name: 'Lưu vào sổ công thức', exact: true }).click();
 let current = await state(page); const recipe = current.recipes.find((entry: any) => entry.name === 'Mây sencha của tiệm');
 expect(recipe.custom).toBe(true);
 await expect(page.locator('.product-art')).toHaveCount(11);
 await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
 if (!current.menu.includes(recipe.id)) await page.locator('.panel').filter({ has: page.getByRole('heading', { name: recipe.name, exact: true }) }).getByRole('button', { name: 'Đưa vào menu', exact: true }).click();
 await closePanel(page);
 await act(page, { type: 'ORDER', customerId: 'an', recipeId: recipe.id, kind: 'takeaway' });
 current = await state(page); const customOrder = current.orders.find((entry: any) => entry.recipeId === recipe.id);
 expect(customOrder).toBeTruthy();
 await page.locator('.order-card').filter({ hasText: 'Mây sencha của tiệm' }).getByRole('button', { name: 'Pha món này', exact: true }).click();
 await expect(page.locator('.drink-art')).toHaveAttribute('src', '/assets/items/sencha-latte.svg');
 await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
 await page.goto('/?gallery');
 for (const name of ['Người', 'Mèo', 'Món & nguyên liệu', 'Nội thất', 'Môi trường', 'Giao diện', 'Hiệu ứng']) {
  await page.getByRole('button', { name, exact: true }).click();
  await page.waitForFunction(() => [...document.images].every(image => image.complete && image.naturalWidth > 0));
  expect(await page.locator('article').count()).toBeGreaterThan(0);
 }
 await page.getByRole('button', { name: 'Mèo', exact: true }).click();
 await expect(page.locator('canvas')).toHaveCount(6);
 await expect.poll(async () => page.locator('canvas').evaluateAll(canvases => canvases.every(element => { const canvas = element as HTMLCanvasElement; return [...canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data].some((value, index) => index % 4 === 3 && value > 0); }))).toBe(true);
 await page.screenshot({ path: `screenshots/gallery-cats-${testInfo.project.name}.png`, fullPage: true });
 expect(brokenAssets).toEqual([]); expect(errors).toEqual([]);
});

test('Xuất JSON trong modal không kích hoạt đồ vật Phaser bên dưới', async ({ page }) => {
 await start(page); await page.getByRole('button', { name: 'Cài đặt', exact: true }).click();
 const exportButton = page.getByRole('button', { name: 'Xuất JSON', exact: true }); await exportButton.scrollIntoViewIfNeeded();
 const downloadPromise = page.waitForEvent('download'); await exportButton.click(); const download = await downloadPromise;
 const downloadPath = await download.path(); expect(downloadPath).toBeTruthy();
 const exported = JSON.parse(await fs.readFile(downloadPath!, 'utf8')); expect(exported.format).toBe('miu-matcha');
 await expect(page.getByRole('dialog')).toHaveAttribute('aria-label', 'Cài đặt & bản lưu');
 await expect(exportButton).toBeVisible();
 expect(await page.getByRole('dialog').count()).toBe(1);
});
