import type { GameState, Incident, IncidentChoice, IngredientId } from './types';
import { post, charge } from './finance';
import { consume, stock } from './inventory';
import { extendedFamilies } from './eventFamilies';
import { random, nextId, log, presentOrders, handoffStaff } from './eventSupport';
export { random, nextId, log, presentOrders } from './eventSupport';

export type Template={type:string;title:string;description:string;sign:string;cause:Incident['cause'];severity:Incident['severity'];fact:string;alternative:string;choices:IncidentChoice[];condition:(s:GameState)=>boolean;participants:(s:GameState)=>string[];lossCash?:number;ingredient?:IngredientId;quantity?:number;onStart?:(s:GameState,i:Incident)=>void;onResolve?:(s:GameState,i:Incident,choiceId:string)=>void};
const choice=(id:string,label:string,description:string,cost=0,duration=12,requiresEvidence?:number):IncidentChoice=>({id,label,description,cost,duration,requiresEvidence});
const waiting=(s:GameState)=>s.orders.filter(o=>['waiting','making','ready'].includes(o.status));
const working=(s:GameState)=>s.staff.filter(w=>w.hired&&!w.former&&w.onShift);
const present=(s:GameState)=>presentOrders(s).slice(0,1).map(o=>o.customerId);
const all:Template[]=[
 {type:'spill',title:'Sàn gần bàn bị ướt',description:'Một ly nước đổ. Khách và nhân viên cần lối đi an toàn.',sign:'Vệt nước ở lối đi; đặt biển trước khi lau.',cause:'accident',severity:'light',fact:'Khách vô tình chạm khuỷu tay vào cốc nước.',alternative:'Không có dấu hiệu phá hoại.',condition:s=>s.hygiene<95,participants:present,choices:[choice('clean','Đặt biển và lau','Vệ sinh +18; 12 giây thao tác.',3000,12),choice('guide','Nhờ nhân viên hướng dẫn lối đi','Vệ sinh +10; nhân viên bớt năng lượng.',0,18)]},
 {type:'lostobject',title:'Một chiếc ví để quên',description:'Khách tưởng ví bị mất. Hãy kiểm tra ghế và sổ giao dịch trước khi kết luận.',sign:'Một chiếc ví dưới ghế; hóa đơn vẫn đủ.',cause:'misunderstanding',severity:'light',fact:'Ví nằm dưới ghế cửa sổ, số tiền quầy khớp hóa đơn.',alternative:'Không có bằng chứng trộm cắp.',condition:s=>waiting(s).length>0,participants:present,choices:[choice('return','Xác minh rồi trả đồ','Cần kiểm tra vật chứng; thiện cảm +8.',0,12,1),choice('explain','Giải thích và giữ ở quầy đồ thất lạc','Ghi nhật ký đồ thất lạc; không buộc tội ai.',0,15)]},
 {type:'count',title:'Kho sữa có số đếm lệch',description:'Phiếu ghi ít hơn kiểm đếm. Đây có thể là sai số nhập liệu.',sign:'Hai nhãn lô giống nhau, số lượng vẫn đủ.',cause:'miscount',severity:'light',fact:'Lô sữa được ghi đúng trong kho; nhân viên đã đếm một lô hai lần.',alternative:'Không có hàng nào bị mất.',condition:s=>stock(s,'milk')>0,participants:s=>working(s).slice(0,1).map(w=>w.id),choices:[choice('recheck','Đếm lại và sửa phiếu','Xác minh số liệu, không ghi tổn thất.',0,20,1),choice('train','Hướng dẫn quy trình nhãn lô','Chi 12.000; giảm sai số lần sau.',12000,25),choice('accuse','Cảnh cáo khi chưa đủ căn cứ','Có thể làm giảm tinh thần và danh tiếng.',0,8)]},
 {type:'mistake',title:'Một phiếu món ghi sai',description:'Nhân viên báo lỗi tự nguyện. Cần phân biệt thiếu đào tạo với hành vi cố ý.',sign:'Nhân viên chủ động để phiếu lỗi riêng và xin hướng dẫn.',cause:'accident',severity:'light',fact:'Nhân viên mới nhầm tên món trên phiếu; không có tiền hay hàng thất thoát.',alternative:'Không có bằng chứng gian lận.',condition:s=>working(s).some(w=>w.trained<1),participants:s=>working(s).filter(w=>w.trained<1).slice(0,1).map(w=>w.id),choices:[choice('mentor','Cho người có kinh nghiệm hướng dẫn','Tay nghề +4, hài lòng +8; 25 giây.',10000,25),choice('recheck','Kiểm tra lại đơn và sửa phiếu','Không mất hàng; giảm áp lực trước khi làm.',0,16),choice('accuse','Cảnh cáo lỗi nghi là gian lận','Không đủ căn cứ sẽ giảm tinh thần đội ngũ.',0,8)]},
 {type:'fatigue',title:'Nhân viên xin đổi ca',description:'Một thành viên mệt và chủ động xin nghỉ ngắn, công việc cần bàn giao.',sign:'Tốc độ giảm, năng lượng thấp; không phải dấu hiệu trộm cắp.',cause:'procedure',severity:'light',fact:'Lịch ca dài và chưa có giờ nghỉ.',alternative:'Nguyên nhân là lịch làm và nhu cầu cá nhân.',condition:s=>working(s).some(w=>w.energy<55),participants:s=>working(s).filter(w=>w.energy<55).slice(0,1).map(w=>w.id),choices:[choice('rest','Cho nghỉ và bàn giao','Năng lượng +30, hài lòng +12; không nhận đơn mới.',0,15),choice('meal','Bữa ăn ca và đổi nhịp','Chi 8.000, phục hồi năng lượng.',8000,20),choice('insist','Giữ nguyên lịch ca','Tiếp tục làm, hài lòng giảm 12.',0,5)]},
 {type:'complaint',title:'Khách phản ánh chất lượng',description:'Khách muốn xem lại phiếu món. Hãy dùng yêu cầu và chất lượng đã ghi để xử lý.',sign:'Khách nhắc nhiệt độ trên phiếu, không yêu cầu tiền ngoài hóa đơn.',cause:'misunderstanding',severity:'light',fact:'Phiếu món và yêu cầu ban đầu vẫn lưu; cần so sánh trước khi hoàn tiền.',alternative:'Có thể là đổi ý sau khi pha.',condition:s=>waiting(s).some(o=>o.status==='ready'),participants:present,choices:[choice('explain','So phiếu và giải thích','Cần kiểm tra đơn; dịch vụ +5.',0,15,1),choice('coupon','Tặng mã giảm giá giới hạn','Chi 5.000 chăm sóc; lần sau được ưu tiên.',5000,10),choice('refund','Hoàn một phần theo dữ kiện','Hoàn tối đa 10.000 trên đơn đã trả, không ghi lặp.',0,10,1)]},
 {type:'catrest',title:'Mèo muốn được nghỉ',description:'Khách vẫn gọi khi mèo quay đầu. Khu nghỉ phải được tôn trọng.',sign:'Đuôi quẫy nhanh, bé tránh bàn tay.',cause:'procedure',severity:'light',fact:'Mèo đã tương tác nhiều và cần góc yên tĩnh.',alternative:'Không phải bé mèo khó tính.',condition:s=>s.cats.some(c=>c.unlocked&&c.energy<65),participants:s=>s.cats.filter(c=>c.unlocked&&c.energy<65).slice(0,1).map(c=>c.id),choices:[choice('rest','Hướng dẫn nội quy và cho mèo nghỉ','Mèo hồi năng lượng, lòng tin +5.',0,15),choice('gate','Kiểm tra cửa ngăn và góc nghỉ','Chi 5.000, giảm rủi ro chạy ra cửa.',5000,20)]},
 {type:'health',title:'Bé mèo có vẻ mệt',description:'Bé nằm nhiều và không muốn chơi. Đây là dấu hiệu trong mô phỏng cần kiểm tra.',sign:'Năng lượng và sức khỏe giảm; cần cho nghỉ.',cause:'accident',severity:'light',fact:'Bé cần nghỉ và kiểm tra bởi bác sĩ thú y trong game.',alternative:'Game không cung cấp chẩn đoán sức khỏe thực tế.',condition:s=>s.cats.some(c=>c.unlocked&&c.health<65),participants:s=>s.cats.filter(c=>c.unlocked&&c.health<65).slice(0,1).map(c=>c.id),choices:[choice('vet','Mời thú y trong game','Chi 25.000, sức khỏe phục hồi.',25000,25),choice('rest','Theo dõi ở góc nghỉ','Năng lượng hồi, sức khỏe +10; chưa phải khám.',0,30)]},
 {type:'fridge',title:'Tủ lạnh chạy không đều',description:'Nhiệt độ tăng sau nhiều ngày không bảo trì. Lô nhạy nhiệt cần được bảo vệ.',sign:'Độ bền tủ lạnh dưới 30; tiếng máy gián đoạn.',cause:'accident',severity:'serious',fact:'Thiết bị hao mòn, không có dấu hiệu nhân viên cố ý làm hỏng.',alternative:'Lô mới vẫn an toàn; lô nhạy nhiệt có nguy cơ hỏng.',condition:s=>s.equipment.some(e=>e.id==='fridge'&&e.durability<30)&&stock(s,'milk')>=60,participants:()=>['technician'],ingredient:'milk',quantity:60,choices:[choice('repair','Sửa và kiểm tra lô','Chi 20.000, tủ lạnh hồi 70 độ bền.',20000,30),choice('isolate','Cách ly và gọi kỹ thuật sau','Ghi rõ hao hụt; còn rủi ro đến khi sửa.',0,12)]},
 {type:'theft',title:'Chênh lệch tiền trong quầy',description:'Đối soát cho thấy tiền mặt thiếu. Chưa biết người gây ra; cần xem vùng camera và phiếu.',sign:'Sổ bán món đủ nhưng quầy thiếu 12.000; mất tiền được ghi riêng.',cause:'theft',severity:'serious',fact:'Đối soát xác nhận 12.000 thiếu, bản ghi chỉ thấy một bàn tay ngoài vùng mặt.',alternative:'Không xác định danh tính chỉ từ hình ảnh hoặc lời đoán.',condition:s=>s.settings.theft&&s.day>1&&s.cash>30000&&waiting(s).length>0,participants:present,lossCash:12000,choices:[choice('record','Ghi tổn thất và đổi quy trình','Đã ghi tổn thất một lần; kiểm tra tiền trước giao đơn.',0,18),choice('verify','Kiểm tra hóa đơn và camera','Cần 2 bằng chứng; giảm rủi ro nhưng camera có vùng hạn chế.',0,25,2),choice('security','Nhờ bảo vệ giả lập xem hồ sơ','Cần 2 bằng chứng; chi 5.000, không kết luận danh tính.',5000,30,2)]},
 {type:'unpaid',title:'Đơn mang đi chưa xác nhận thanh toán',description:'Khách vội nhận nhầm túi. Kiểm tra mã và nhắc thanh toán trước khi giao.',sign:'Mã túi không khớp phiếu; món vẫn ở kệ.',cause:'procedure',severity:'light',fact:'Khách nhầm túi cùng màu. Món vẫn trong quán, chưa có tổn thất.',alternative:'Nhầm lẫn chưa phải trộm cắp.',condition:s=>waiting(s).some(o=>o.kind!=='table'),participants:present,choices:[choice('verify','Xác minh mã đơn','Cần xem phiếu; không mất hàng hay thu tiền ngoài đơn.',0,12,1),choice('explain','Giải thích quy trình trả trước','Cài dấu xác minh, giảm nhầm túi lần sau.',0,20)]},
 {type:'supplier',title:'Lô hàng cần kiểm nhãn',description:'Nhà cung cấp báo một số hộp không đúng chất lượng cam kết.',sign:'Nhãn và tình trạng lô chưa thống nhất; cách ly để tránh dùng nhầm.',cause:'procedure',severity:'light',fact:'Lô giao có chất lượng thấp hơn nhãn; có thể đổi hoặc nhận bồi thường có giới hạn.',alternative:'Lỗi nhà cung cấp không phải sai sót nhân viên.',condition:s=>s.deliveries.some(d=>d.status==='arrived'&&d.quality<(d.expectedQuality??d.quality)),participants:()=>['courier'],choices:[choice('return','Cách ly lô và trả nhà cung cấp','Hoàn tiền phần hàng còn lại; lô không được pha.',0,25,1),choice('inspect','Kiểm từng nhãn và nhận hàng đã xác minh','Lần nhập sau chọn nguồn dự phòng.',0,22,1)]},
 {type:'fraud',title:'Phiếu hủy bất thường',description:'Một phiếu không khớp sổ. Chỉ xác minh giao dịch trước khi xử lý người liên quan.',sign:'Phiếu hủy thiếu mã đơn; hàng và tiền chưa bị trừ.',cause:'fraud',severity:'serious',fact:'Phiếu được lập cố ý ngoài quy trình; đối soát và trao đổi riêng xác nhận vi phạm, chưa phát sinh thất thoát.',alternative:'Chỉ sau xác minh hai nguồn mới phân biệt với nhập nhầm.',condition:s=>s.settings.fraud&&s.day>=4&&working(s).length>0&&s.flags.audit!==true,participants:s=>working(s).slice(0,1).map(w=>w.id),choices:[choice('recheck','Đối soát và trao đổi riêng','Cần hai bằng chứng; chặn phiếu trước khi chi.',0,30,2),choice('restrict','Tạm ngừng tác vụ nhạy cảm','Chưa kết luận; nhân viên vẫn có thể làm việc khác.',0,15),choice('warn','Cảnh cáo sau khi xác minh','Cần hai bằng chứng; lưu hồ sơ, cho cơ hội sửa.',0,20,2)]},
 {type:'positive',title:'Khách quen giới thiệu Miu',description:'Một khách quay lại cùng lời giới thiệu quán, tạo làn khách trong những ngày sau.',sign:'Khách nhắc món mình thích và tên bé mèo quen.',cause:'positive',severity:'positive',fact:'Lượt ghé và thiện cảm được ghi trong lịch sử.',alternative:'Danh tiếng tăng nhờ dịch vụ đã thực hiện.',condition:s=>waiting(s).some(o=>s.customers[o.customerId].visits>=2),participants:s=>waiting(s).filter(o=>s.customers[o.customerId].visits>=2).slice(0,1).map(o=>o.customerId),choices:[choice('thanks','Cảm ơn và giữ lời hứa chất lượng','Danh tiếng +5, làn khách tăng hai ngày.',0,10),choice('community','Mời buổi trà cộng đồng','Chi 12.000; danh tiếng +8 và mở câu chuyện.',12000,20)]},
 {type:'mentor',title:'Nhân viên đề xuất cải tiến',description:'Một người có kinh nghiệm muốn hướng dẫn đồng nghiệp mới và thử món riêng.',sign:'Có ghi chú thời gian thao tác cùng công thức, không tự ý đổi menu.',cause:'positive',severity:'positive',fact:'Kinh nghiệm tăng từ các tác vụ thật đã hoàn thành.',alternative:'Sáng kiến cần được duyệt trước khi áp dụng.',condition:s=>working(s).some(w=>w.experience>=3),participants:s=>working(s).filter(w=>w.experience>=3).slice(0,1).map(w=>w.id),choices:[choice('mentor','Chấp thuận giờ hướng dẫn','Tay nghề và hài lòng tăng; tiết kiệm lần sau.',5000,25),choice('thanks','Ghi nhận sáng kiến','Hài lòng +8, giữ đề xuất trong nhật ký.',0,10)]},
 {type:'birthday',title:'Sinh nhật Matcha',description:'Nhật ký mèo nhắc ngày kỷ niệm của bé. Có thể tổ chức nhẹ nhàng trong giờ vắng.',sign:'Matcha đã thân thiết hơn và yêu trò cần câu.',cause:'positive',severity:'positive',fact:'Sự kiện kỷ niệm ngày 3, chỉ thưởng một lần.',alternative:'Bé được nghỉ khi mệt; quà không bắt buộc.',condition:s=>s.day===3&&!s.flags.birthday,participants:()=>['matcha'],choices:[choice('celebrate','Góc ảnh và đồ chơi mới','Chi 10.000; thân thiết +8, ảnh kỷ niệm.',10000,20),choice('quiet','Mừng sinh nhật ở góc nghỉ','Thân thiết +4, không gây ồn.',0,12)]},
 {type:'market',title:'Thông báo giá sữa ngày mai',description:'Nhà cung cấp báo giá sữa tăng 10% trong hai ngày, cho quán thời gian chuẩn bị.',sign:'Bảng giá có ngày hiệu lực; hàng trong kho giữ nguyên giá vốn.',cause:'procedure',severity:'light',fact:'Nguồn hàng công bố giá trước, không đổi chi phí lô đã mua.',alternative:'Có thể đổi nguồn hoặc giữ menu nhỏ.',condition:s=>s.day>=2&&s.flags.marketUntil!==s.day+2,participants:()=>['courier'],choices:[choice('backup','Giữ nguồn dự phòng','Nguồn tiết kiệm bù một phần biến động.',0,15),choice('menu','Theo dõi giá và thu hẹp menu','Ghi kế hoạch, không tự ý tăng giá bán.',0,12)]},
 {type:'community',title:'Khu phố có lễ hội trà',description:'Một lễ hội nhỏ thu hút khách yêu trà trong hai ngày tới.',sign:'Tờ chương trình nêu lịch và đơn vị tổ chức.',cause:'positive',severity:'positive',fact:'Nhu cầu đồ uống tăng có thời hạn, không sinh doanh thu nếu chưa bán.',alternative:'Quán cần đủ kho và chỗ ngồi.',condition:s=>s.day>=5&&s.flags.festivalUntil!==s.day+2,participants:()=>['courier'],choices:[choice('join','Đăng ký góc trà tại quán','Chi 15.000; nhu cầu tăng 2 ngày.',15000,20),choice('prepare','Chuẩn bị menu hiện tại','Tăng nhu cầu nhẹ, không nhận đơn quá kho.',0,15)]},
];
const templates=[...all,...extendedFamilies];
export const incidentTemplates=templates.map(t=>({type:t.type,title:t.title,description:t.description,choices:t.choices}));

/** Authoring / test entry point uses the same eligibility, ledger and stored coordinator as the scheduler. */
export function triggerIncident(state:GameState,type:string):Incident|null {
 const template=templates.find(t=>t.type===type);if(!template||!template.condition(state)||state.phase!=='open'||state.incidents.some(i=>i.stage!=='resolved'))return null;
 if(state.day===1&&template.severity==='serious'||template.cause==='theft'&&!state.settings.theft||template.cause==='fraud'&&!state.settings.fraud)return null;
 const id=nextId(state,'incident');const incident:Incident={id,type:template.type,title:template.title,description:template.description,sign:template.sign,stage:'observed',createdAt:state.clock,day:state.day,severity:template.severity,participants:template.participants(state),cause:template.cause,lossCash:template.lossCash??0,lossIngredient:template.ingredient,lossQuantity:template.quantity??0,insuranceEligible:state.insured,evidence:[{id:'record',label:'Đối chiếu sổ / phiếu',fact:template.fact,confidence:55,checked:false},{id:'witness',label:'Trao đổi riêng / kiểm tra hiện trường',fact:template.alternative,confidence:35,checked:false}],choices:structuredClone(template.choices)};
 if(['theft','unpaid','lostobject','stockloss','decorloss','unpaidmeal'].includes(incident.type)&&(state.equipment.find(e=>e.id==='camera')?.level??0)>0)incident.evidence.push({id:'camera',label:'Camera vùng cửa / quầy',fact:'Bản ghi quan sát cửa và quầy; không thấy bàn khuất, không xác định người chỉ từ bàn tay hay diện mạo.',confidence:25,checked:false});
 if(incident.lossCash){post(state,{id:`loss:${id}`,category:'loss',label:`Chênh lệch xác nhận: ${incident.title}`,cash:-incident.lossCash,expense:incident.lossCash});}
 if(incident.lossIngredient&&incident.lossQuantity){const used=consume(state.inventory,{[incident.lossIngredient]:incident.lossQuantity},state.day);if(!used)return null;state.inventory=used.batches;post(state,{id:`loss-stock:${id}`,category:'waste',label:`Hao hụt đã kiểm đếm: ${incident.title}`,cogs:used.cost,ingredient:incident.lossIngredient,quantity:incident.lossQuantity});}
 if(template.type==='complaint'){const o=waiting(state).find(o=>o.status==='ready');if(o){incident.orderId=o.id;incident.participants=[o.customerId];}}
 if(template.type==='unpaid'){const o=waiting(state).find(o=>o.kind!=='table');if(o){incident.orderId=o.id;incident.participants=[o.customerId];}}
 if(template.type==='supplier'){const d=state.deliveries.find(d=>d.status==='arrived'&&d.quality<(d.expectedQuality??d.quality));if(d){incident.deliveryId=d.id;const b=state.inventory.find(b=>b.id===d.batchId);if(b)b.quarantined=true;d.status='quarantined';}}
 template.onStart?.(state,incident);state.incidents.push(incident);state.flags['event-day:'+type]=state.day;
 if(incident.severity==='serious')state.flags.lastSerious=state.clock;
 if(template.type==='market'){state.flags.marketStart=state.day+1;state.flags.marketUntil=state.day+2;}
 log(state,`${incident.title}: ${incident.sign}`,'event');return incident;
}

export function maybeIncident(state:GameState):void {
 if(state.phase!=='open'||state.clock<state.nextIncidentAt||state.incidents.some(i=>i.stage!=='resolved'))return;
 const interval={low:260,medium:170,high:110}[state.settings.eventFrequency];state.nextIncidentAt=state.clock+interval;
 const eligible=templates.filter(t=>t.condition(state)&&Number(state.flags['event-day:'+t.type]??0)<state.day&&(state.day>1||t.severity!=='serious')&&(t.severity!=='serious'||state.clock-Number(state.flags.lastSerious??-500)>240)&&(t.cause!=='theft'||state.settings.theft)&&(t.cause!=='fraud'||state.settings.fraud));
 if(!eligible.length)return;const weighted=eligible.map(t=>({template:t,weight:t.type==='theft'?1/(1+(state.equipment.find(e=>e.id==='camera')?.level??0)+(state.equipment.find(e=>e.id==='register')?.level??1)*.3+(state.flags.verifyPickup?1:0)):t.type==='fraud'&&state.flags.training?.5:1}));let roll=random(state)*weighted.reduce((n,v)=>n+v.weight,0);let template=weighted.at(-1)!.template;for(const entry of weighted){roll-=entry.weight;if(roll<=0){template=entry.template;break;}}
 triggerIncident(state,template.type);
}
export function beginResolution(state:GameState,incidentId:string,choiceId:string):void {
 const incident=state.incidents.find(i=>i.id===incidentId);if(!incident||incident.stage==='resolved'||incident.resolving)return;
 const selected=incident.choices.find(c=>c.id===choiceId);if(!selected)return;
 if((selected.requiresEvidence??0)>incident.evidence.filter(e=>e.checked).length){state.lastMessage='Cần kiểm tra đủ bằng chứng trước khi chọn cách xử lý này.';return;}
 if(selected.cost&&!charge(state,`resolve-cost:${incident.id}`,selected.cost,selected.label,'management'))return;
 incident.stage='investigating';incident.resolving={choice:choiceId,remaining:selected.duration};log(state,`Đang ${selected.label.toLowerCase()} (${selected.duration} giây).`,'event');
}
export function completeResolution(state:GameState,i:Incident):void {
 const choiceId=i.resolving?.choice;if(!choiceId||i.stage==='resolved')return;
 i.resolvedChoice=choiceId;i.stage='resolved';i.resolving=undefined;
 const involved=state.staff.filter(w=>i.participants.includes(w.id)&&w.hired&&!w.former),cat=state.cats.find(c=>i.participants.includes(c.id));
 if(choiceId==='accuse'&&(i.cause!=='fraud'||i.evidence.filter(e=>e.checked).length<2)){for(const w of state.staff.filter(w=>w.hired&&!w.former)){w.satisfaction=Math.max(0,w.satisfaction-12);w.history.push(`Ngày ${state.day}: bị nghi ngờ thiếu căn cứ.`);}state.reputation=Math.max(0,state.reputation-5);i.outcome='Sổ khớp. Kết luận thiếu căn cứ làm tinh thần đội ngũ giảm; hồ sơ ghi là sai sót / hiểu lầm, không phải gian lận.';}
 else {i.outcome='Đã xử lý theo dữ kiện; quyết định được lưu trong hồ sơ.';}
 if(['recheck','verify','security','explain','inspect'].includes(choiceId)){state.flags.audit=true;state.flags.verifyPickup=true;}
 if(['train','mentor'].includes(choiceId)){for(const w of involved){w.skill=Math.min(100,w.skill+4);w.trained++;w.satisfaction=Math.min(100,w.satisfaction+8);w.history.push(`Ngày ${state.day}: được hướng dẫn sau ${i.title}.`);}state.flags.training=true;}
 if(choiceId==='restrict')for(const w of involved)w.sensitiveAllowed=false;
 if(choiceId==='warn')for(const w of involved){w.warnings++;w.history.push(`Ngày ${state.day}: cảnh cáo có hồ sơ đã xác minh.`);}
 if(choiceId==='rest'&&i.type!=='resignation'){for(const w of involved){handoffStaff(state,w);w.onShift=false;w.energy=Math.min(100,w.energy+30);w.satisfaction=Math.min(100,w.satisfaction+12);}if(cat){cat.energy=Math.min(100,cat.energy+25);cat.health=Math.min(100,cat.health+10);cat.trust=Math.min(100,cat.trust+5);cat.restingUntil=state.clock+60;}}
 if(choiceId==='meal')for(const w of involved){w.energy=Math.min(100,w.energy+30);w.satisfaction=Math.min(100,w.satisfaction+10);}
 if(choiceId==='insist')for(const w of involved)w.satisfaction=Math.max(0,w.satisfaction-12);
 if(i.type==='spill'){state.hygiene=Math.min(100,state.hygiene+(choiceId==='clean'?18:10));state.flags.floorSafe=true;}
 if(choiceId==='vet'&&cat){cat.health=100;cat.energy=95;cat.restingUntil=state.clock+60;}
 if(choiceId==='gate'){const gate=state.equipment.find(e=>e.id==='catgate');if(gate)gate.durability=100;}
 if(i.type==='fridge'&&choiceId==='repair'){const fridge=state.equipment.find(e=>e.id==='fridge');if(fridge){fridge.durability=90;fridge.broken=false;}}
 if(i.type==='lostobject'&&choiceId==='return'){state.flags.returnedWallet=true;state.reputation=Math.min(100,state.reputation+5);i.outcome='Đồ để quên được trả lại sau xác minh; hiểu lầm đã rõ, không có trộm cắp.';}
 if(i.type==='positive'){state.flags.publicityUntil=state.day+2;state.reputation=Math.min(100,state.reputation+(choiceId==='community'?8:5));}
 if(i.type==='birthday'){state.flags.birthday=true;const matcha=state.cats.find(c=>c.id==='matcha')!;matcha.trust=Math.min(100,matcha.trust+(choiceId==='celebrate'?8:4));if(choiceId==='celebrate')state.album.push({id:nextId(state,'photo'),catId:'matcha',day:state.day,caption:'Sinh nhật Matcha',pose:'chuông và cần câu'});}
 if(i.type==='market'&&choiceId==='backup')state.flags.backupSupplier=true;
 if(i.type==='mentor'){state.flags.processUntil=state.day+2;if(choiceId==='thanks')for(const w of involved)w.satisfaction=Math.min(100,w.satisfaction+8);}
 if(i.type==='complaint'){const order=state.orders.find(o=>o.id===i.orderId);if(order){order.serviceAdjustment=(order.serviceAdjustment??0)+5;if(choiceId==='refund')order.discount=Math.min(10000,order.price);if(choiceId==='coupon')state.flags['coupon:'+order.customerId]=5000;}i.outcome=choiceId==='refund'?'Phiếu chưa thanh toán được giảm tối đa 10.000; không hoàn tiền chưa thu.':'Đã xử lý trên phiếu liên quan và lưu phản hồi.';}
 if(i.type==='community')state.flags.festivalUntil=state.day+2;
 if(i.type==='workshop'){const fees=i.participants.length*20000;post(state,{id:`workshop-sale:${i.id}`,category:'workshop-sales',label:`Phí workshop · ${i.participants.length} người đã tham dự`,cash:fees,revenue:fees});state.reputation=Math.min(100,state.reputation+6);state.xp+=20;state.level=Math.min(6,1+Math.floor(state.xp/80));for(const id of i.participants){const h=state.customers[id];if(h){h.affinity=Math.min(100,h.affinity+5);h.story=Math.min(2,h.story+1);}}for(const w of state.staff.filter(w=>w.hired&&!w.former))w.skill=Math.min(100,w.skill+2);i.outcome='Workshop hoàn thành; phí tham dự, trà/sữa và vật tư đã ghi vào cùng sổ quán.';}
 if(i.type==='supplier'){const d=state.deliveries.find(d=>d.id===i.deliveryId);if(d&&d.batchId){const b=state.inventory.find(b=>b.id===d.batchId);if(b&&choiceId==='return'){post(state,{id:`return:${d.id}`,category:'inventory-return',label:'Hoàn lô nhập còn nguyên',cash:b.quantity*b.unitCost});state.inventory=state.inventory.filter(n=>n.id!==b.id);d.status='returned';}if(choiceId==='inspect'){d.inspected=true;d.status='arrived';if(b)b.quarantined=false;}}}
 templates.find(t=>t.type===i.type)?.onResolve?.(state,i,choiceId);
 const loss=state.transactions.filter(t=>[ `loss:${i.id}`,`loss-stock:${i.id}`,`asset-loss:${i.id}`].includes(t.id)).reduce((n,t)=>n+t.expense+t.cogs,0);
 if(loss&&i.insuranceEligible&&state.insured&&i.evidence.every(e=>e.checked)&&state.insuranceClaimDay!==state.day){const covered=Math.min(10000,Math.round(loss*.7));post(state,{id:`insurance:${i.id}`,category:'insurance',label:'Bồi thường bảo hiểm giả lập',cash:covered,expense:-covered});state.insuranceClaimDay=state.day;i.outcome+=' Bảo hiểm bồi thường 70%, giới hạn 10.000/ngày.';}
 for(const w of involved)w.history.push(`Ngày ${state.day}: ${i.title} — ${i.outcome}`);
 log(state,`${i.title}: ${i.outcome}`,'event');
}
