import {describe,it,expect} from 'vitest';
import { createGame, reduceGame, stock, consume, recipes, customers, scoreDrink, reportDay, canPlace, activeOrders } from '../src/domain';
import type {GameState,GameAction,Incident} from '../src/domain';
import {maybeIncident} from '../src/domain/events';

const act=(s:GameState,a:GameAction)=>reduceGame(s,a);
const advance=(s:GameState,seconds:number)=>{for(let n=0;n<seconds;n+=60)s=act(s,{type:'STEP',seconds:Math.min(60,seconds-n)});return s;};
const open=()=>act(createGame({seed:321}),{type:'OPEN'});
function prepared(recipe='matcha-latte',customer='linh'):GameState {let s=open();s=act(s,{type:'ORDER',customerId:customer,recipeId:recipe});s=act(s,{type:'START_DRINK',orderId:s.orders[0].id});return s;}
function served(recipe='matcha-latte',customer='linh'):GameState {let s=prepared(recipe,customer);s=act(s,{type:'FINISH_DRINK',orderId:s.orders[0].id,technique:95});return act(s,{type:'SERVE',orderId:s.orders[0].id});}
function incidentFixture(type='theft',cause:Incident['cause']='theft'):Incident{return {id:'test-incident',type,title:'Kiểm tra',description:'Bản ghi kiểm tra',sign:'Có chênh lệch',stage:'observed',createdAt:0,day:1,severity:'serious',participants:['lan'],cause,lossCash:12000,lossQuantity:0,evidence:[{id:'record',label:'Sổ',fact:'Có bản ghi',confidence:60,checked:false},{id:'witness',label:'Xác minh',fact:'Đã kiểm tra',confidence:30,checked:false}],choices:[{id:'verify',label:'Xác minh',description:'Đối chiếu hai nguồn',cost:0,duration:5,requiresEvidence:2},{id:'record',label:'Ghi tổn thất',description:'Không ghi lặp',cost:0,duration:5},{id:'accuse',label:'Buộc tội',description:'Rủi ro thiếu căn cứ',cost:0,duration:5}]};}

describe('kho và giá vốn',()=>{
 it('dùng lô sắp hết hạn trước và không đổi dữ liệu nguồn',()=>{const batches=[{id:'new',ingredient:'milk' as const,quantity:100,unitCost:40,expiresDay:5,quality:90},{id:'old',ingredient:'milk' as const,quantity:50,unitCost:30,expiresDay:2,quality:80}];const result=consume(batches,{milk:80},1)!;expect(result.cost).toBe(2700);expect(result.batches.find(b=>b.id==='new')!.quantity).toBe(70);expect(result.batches.some(b=>b.id==='old')).toBe(false);expect(batches[0].quantity).toBe(100);});
 it('thiếu một nguyên liệu thì toàn bộ giao dịch kho bị từ chối',()=>{const s=open(),before=structuredClone(s.inventory);s.inventory=s.inventory.filter(b=>b.ingredient!=='milk');const inventory=structuredClone(s.inventory);const result=consume(s.inventory,{matcha:3,milk:140},1);expect(result).toBeNull();expect(s.inventory).toEqual(inventory);expect(before.length).toBeGreaterThan(inventory.length);});
 it('không dùng lô hết hạn hoặc cách ly',()=>{const s=createGame();s.inventory=[{id:'x',ingredient:'milk',quantity:100,unitCost:35,expiresDay:0,quality:90},{id:'y',ingredient:'milk',quantity:100,unitCost:35,expiresDay:3,quality:90,quarantined:true}];expect(stock(s,'milk')).toBe(0);expect(consume(s.inventory,{milk:1},s.day)).toBeNull();});
 it('mua kho giảm tiền mặt nhưng chưa tính giá vốn hay chi phí lợi nhuận',()=>{const s=createGame(),next=act(s,{type:'BUY_INGREDIENT',ingredient:'matcha',quantity:50,supplierId:'local'});expect(next.cash).toBe(s.cash-9000);expect(reportDay(next).profit).toBe(0);expect(stock(next,'matcha')).toBe(stock(s,'matcha'));const arrived=advance(next,28);expect(stock(arrived,'matcha')).toBe(150);});
 it('pha chỉ trừ một lần; bỏ món thành hao hụt từng nguyên liệu và pha lại có chi phí mới',()=>{let s=prepared(),id=s.orders[0].id;const tea=stock(s,'matcha'),cost=reportDay(s).cogs;s=act(s,{type:'START_DRINK',orderId:id});expect(stock(s,'matcha')).toBe(tea);expect(reportDay(s).cogs).toBe(cost);s=act(s,{type:'DISCARD',orderId:id});expect(reportDay(s).cogs).toBe(cost);expect(reportDay(s).waste.some(w=>w.ingredient==='matcha'&&w.quantity===3)).toBe(true);s=act(s,{type:'START_DRINK',orderId:id});expect(stock(s,'matcha')).toBe(tea-3);expect(reportDay(s).cogs).toBe(cost*2);});
 it('sửa món chỉ thêm thật; không lấy lại sữa hoặc đổi trà đã rót',()=>{let s=prepared(),id=s.orders[0].id;const f=s.orders[0].draft!.formula,tea=stock(s,'matcha');s=act(s,{type:'ADJUST_DRINK',orderId:id,patch:{tea:'houjicha'}});expect(s.orders[0].draft!.formula.tea).toBe('matcha');s=act(s,{type:'ADJUST_DRINK',orderId:id,patch:{milkAmount:1}});expect(s.orders[0].draft!.formula.milkAmount).toBe(f.milkAmount);const sugar=stock(s,'sugar');s=act(s,{type:'ADJUST_DRINK',orderId:id,patch:{sugar:f.sugar+5}});expect(stock(s,'sugar')).toBe(sugar-5);expect(stock(s,'matcha')).toBe(tea);});
 it('hết hạn qua ngày tạo hao hụt một lần và kho không âm',()=>{let s=createGame();s.inventory.find(b=>b.ingredient==='milk')!.expiresDay=1;s=act(s,{type:'OPEN'});s=act(s,{type:'CLOSE'});s=act(s,{type:'NEXT_DAY'});expect(stock(s,'milk')).toBe(0);expect(s.transactions.filter(t=>t.id.startsWith('expire:'))).toHaveLength(1);const count=s.transactions.length;s=act(s,{type:'NEXT_DAY'});expect(s.transactions.length).toBe(count);expect(s.inventory.every(b=>b.quantity>=0)).toBe(true);});
});
describe('điểm và đơn hàng',()=>{
 it('điểm có trọng số 30/30/20/10/10, kỹ thuật và nhiệt độ làm thay đổi thật',()=>{const f={...recipes[0].formula,dissolution:100,presentation:100},customer=customers[0],order={requested:f};const best=scoreDrink(f,order,customer,100);expect(best).toMatchObject({requirement:30,taste:30,technique:20,temperature:10,presentation:10,total:100});expect(scoreDrink({...f,dissolution:0},order,customer,0).total).toBe(80);expect(scoreDrink({...f,temperature:70},order,customer,100).temperature).toBe(0);expect(scoreDrink({...f,sugar:45},order,customer,100).total).toBeLessThan(80);});
 it('pha được matcha lẫn houjicha và giao mỗi đơn chỉ thu tiền một lần',()=>{for(const [recipe,customer] of [['matcha-latte','linh'],['houjicha-latte','an']]){let s=served(recipe,customer);expect(s.orders[0].status).toBe('served');expect(s.orders[0].score!.total).toBeGreaterThan(85);const cash=s.cash;s=act(s,{type:'SERVE',orderId:s.orders[0].id});expect(s.cash).toBe(cash);expect(s.transactions.filter(t=>t.id===`sale:${s.orders[0].id}`)).toHaveLength(1);}});
 it('chặn thành phần khách yêu cầu tránh và ghi nhận dùng sữa yến mạch đúng',()=>{let s=open();s=act(s,{type:'ORDER',customerId:'mai',recipeId:'matcha-latte'});expect(s.orders[0].requested.milk).toBe('oat');s=act(s,{type:'START_DRINK',orderId:s.orders[0].id,formula:{...s.orders[0].requested,milk:'milk'}});s=act(s,{type:'FINISH_DRINK',orderId:s.orders[0].id,technique:90});const cash=s.cash;s=act(s,{type:'SERVE',orderId:s.orders[0].id});expect(s.cash).toBe(cash);expect(s.orders[0].status).toBe('ready');expect(s.lastMessage).toContain('Chặn giao');});
 it('tạm dừng không hao thời gian, kho hay nhu cầu mèo',()=>{const s=act(prepared(),{type:'PAUSE',paused:true});expect(advance(s,60)).toEqual(s);});
 it('khách chờ quá lâu rời đi; món đã pha thành hao hụt',()=>{let s=prepared();s.orders[0].remaining=2;s=advance(s,3);expect(s.orders[0].status).toBe('left');expect(reportDay(s).lost).toBe(1);expect(reportDay(s).waste.length).toBeGreaterThan(0);});
});
describe('bánh và mèo',()=>{
 it('nướng đúng lúc tạo bánh chất lượng cao; không thể nhận mẻ hai lần',()=>{let s=createGame();s=act(s,{type:'BAKE',cakeId:'cookie'});const id=s.baking[0].id;s=advance(s,44);s=act(s,{type:'TAKE_BAKE',bakingId:id,decoration:100});expect(s.cakes[0].quality).toBe(98);expect(s.cakes[0].quantity).toBe(4);const cost=reportDay(s).cogs;s=act(s,{type:'TAKE_BAKE',bakingId:id});expect(s.cakes).toHaveLength(1);expect(reportDay(s).cogs).toBe(cost);});
 it('bánh cháy không phát thưởng hoặc ghi giá vốn hai lần',()=>{let s=act(createGame(),{type:'BAKE',cakeId:'cookie'});const cost=reportDay(s).cogs;s=advance(s,60);s=act(s,{type:'TAKE_BAKE',bakingId:s.baking[0].id});expect(s.baking[0].status).toBe('burned');expect(s.cakes).toHaveLength(0);expect(reportDay(s).cogs).toBe(cost);expect(reportDay(s).waste.length).toBeGreaterThan(0);});
 it('mỗi bé có phản hồi và thời gian nghỉ khác nhau; bấm lặp không tăng thân thiết',()=>{const responses=[];for(const id of ['matcha','houji','mochi']){let s=createGame();s=act(s,{type:'CAT_INTERACT',catId:id,interaction:id==='matcha'?'chin':id==='mochi'?'cheek':'head'});const c=s.cats.find(c=>c.id===id)!;responses.push(c.expression);const trust=c.trust;s=act(s,{type:'CAT_INTERACT',catId:id,interaction:'head'});expect(s.cats.find(c=>c.id===id)!.trust).toBe(trust);}expect(new Set(responses).size).toBeGreaterThan(1);});
 it('mèo thưởng tối đa ba lượt/ngày và không sinh tiền vô hạn',()=>{let s=createGame(),cash=s.cash;for(let i=0;i<4;i++){s=act(s,{type:'CAT_GAME',catId:'matcha',game:'feather',score:100});s=advance(s,31);}expect(s.cats[0].gamesToday).toBe(3);expect(s.cats[0].trust).toBeGreaterThan(30);expect(s.cash).toBe(cash);});
 it('nút cho nghỉ chỉ thưởng lòng tin một lần, không thể farm',()=>{let s=act(createGame(),{type:'CAT_INTERACT',catId:'matcha',interaction:'chin'});s=act(s,{type:'CAT_INTERACT',catId:'matcha',interaction:'rest'});const trust=s.cats[0].trust;for(let i=0;i<20;i++)s=act(s,{type:'CAT_INTERACT',catId:'matcha',interaction:'rest'});expect(s.cats[0].trust).toBe(trust);});
});
describe('nhân viên và bàn giao',()=>{
 it('nhân viên nhận tác vụ độc quyền, dùng nguyên liệu một lần, tạo món sau thời gian thật',()=>{let s=open();s=act(s,{type:'HIRE',staffId:'lan'});s=act(s,{type:'HIRE',staffId:'quang'});s=act(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});const id=s.orders[0].id;s=act(s,{type:'ASSIGN',staffId:'lan',task:'drink',targetId:id});const cost=reportDay(s).cogs;s=act(s,{type:'ASSIGN',staffId:'quang',task:'drink',targetId:id});expect(s.tasks.filter(t=>t.targetId===id)).toHaveLength(1);expect(reportDay(s).cogs).toBe(cost);s=advance(s,20);expect(s.orders[0].status).toBe('ready');expect(s.staff[0].experience).toBe(1);});
 it('sa thải giữa ca giữ món, trả nghĩa vụ một lần và không làm thêm',()=>{let s=open();s=act(s,{type:'HIRE',staffId:'lan'});s=act(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});s=act(s,{type:'ASSIGN',staffId:'lan',task:'drink',targetId:s.orders[0].id});s=advance(s,5);const tea=stock(s,'matcha');s=act(s,{type:'FIRE',staffId:'lan',reason:'Điều chỉnh ca',confirm:true});const cash=s.cash;expect(s.staff[0].former).toBe(true);expect(s.tasks[0].status).toBe('handed-over');expect(s.orders[0].worker).toBeUndefined();expect(stock(s,'matcha')).toBe(tea);s=act(s,{type:'FIRE',staffId:'lan',reason:'Bấm lại',confirm:true});expect(s.cash).toBe(cash);s=act(s,{type:'FINISH_DRINK',orderId:s.orders[0].id,technique:90});s=act(s,{type:'SERVE',orderId:s.orders[0].id});expect(s.orders[0].status).toBe('served');s=advance(s,20);expect(s.staff[0].secondsWorked).toBe(5);s=act(s,{type:'CLOSE'});s=act(s,{type:'CLOSE'});expect(s.transactions.filter(t=>t.category==='salary')).toHaveLength(1);});
 it('người chăm mèo tiêu hao thức ăn khi nhận việc và không trừ lần hai',()=>{let s=createGame();s=act(s,{type:'HIRE',staffId:'khoa'});const before=stock(s,'catfood');s=act(s,{type:'ASSIGN',staffId:'khoa',task:'cat',targetId:'matcha'});expect(stock(s,'catfood')).toBe(before-15);s=act(s,{type:'ASSIGN',staffId:'khoa',task:'cat',targetId:'matcha'});expect(stock(s,'catfood')).toBe(before-15);s=advance(s,18);expect(stock(s,'catfood')).toBe(before-15);expect(s.tasks[0].claimed).toBe(true);});
 it('đóng quán bàn giao tác vụ còn lại, ghi lương / thuế một lần',()=>{let s=open();s=act(s,{type:'HIRE',staffId:'lan'});s=act(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});s=advance(s,3);s=act(s,{type:'CLOSE'});s=act(s,{type:'CLOSE'});expect(s.tasks.every(t=>t.status!=='working')).toBe(true);expect(s.staff[0].taskId).toBeUndefined();const count=s.transactions.length,cash=s.cash;s=act(s,{type:'CLOSE'});expect(s.transactions.length).toBe(count);expect(s.cash).toBe(cash);expect(s.transactions.filter(t=>t.category==='tax')).toHaveLength(1);});
});
describe('tài chính và nội thất',()=>{
 it('lợi nhuận / tiền mặt tách nhau; hoàn tiền, vay, đầu tư và thuế đối soát đúng',()=>{let s=served(),id=s.orders[0].id;s=act(s,{type:'REFUND',orderId:id,amount:5000});s=act(s,{type:'LOAN',amount:100000});s=act(s,{type:'BUY_FURNITURE',kind:'plant'});s=act(s,{type:'CLOSE'});s=act(s,{type:'CLOSE'});const r=s.reports[0];expect(r.netRevenue).toBe(s.orders[0].price-5000);expect(r.tax).toBe(Math.round(r.netRevenue*.05));expect(r.profit).toBe(r.netRevenue-r.cogs-r.operating-r.tax);expect(r.financing).toBe(100000);expect(r.investment).toBe(40000);expect(r.endCash).toBe(s.cash);expect(r.endCash-r.startCash).toBe(r.cashFlow);});
 it('thay đổi sau giờ làm cập nhật dòng tiền báo cáo, ngày mới giữ tiền đầu ngày đúng',()=>{let s=act(open(),{type:'CLOSE'});s=act(s,{type:'BUY_FURNITURE',kind:'plant'});expect(s.reports[0].endCash).toBe(s.cash);const cash=s.cash;s=act(s,{type:'NEXT_DAY'});expect(s.startCash).toBe(cash);expect(s.day).toBe(2);});
 it('ngăn cửa / quầy / va chạm; nội thất hợp lệ thay sức chứa',()=>{let s=createGame();expect(canPlace(s,'table',7,10).valid).toBe(false);expect(canPlace(s,'table',3,5).valid).toBe(false);expect(canPlace(s,'table',1,1).valid).toBe(false);expect(canPlace(s,'cushion',1,8).valid).toBe(false);s=act(s,{type:'BUY_FURNITURE',kind:'table'});const id=s.storage[0].id;s=act(s,{type:'PLACE_FURNITURE',furnitureId:id,x:1,y:8,rotation:90});expect(s.furniture.some(f=>f.id===id)).toBe(true);expect(s.storage).toHaveLength(0);});
 it('quỹ dự phòng và trả gốc vay không làm tăng doanh thu / chi phí',()=>{let s=createGame();s=act(s,{type:'LOAN',amount:100000});const loan=s.loans[0];s=act(s,{type:'RESERVE',amount:50000});s=act(s,{type:'REPAY',loanId:loan.id,amount:25000});expect(reportDay(s).revenue).toBe(0);expect(reportDay(s).profit).toBe(0);expect(s.reserve).toBe(50000);expect(s.loans[0].remaining).toBe(75000);});
});
describe('sự kiện có dữ kiện',()=>{
 it('hai quán cùng seed giữ lịch khách / sự cố giống nhau; tải snapshot không tạo lại biến cố',()=>{let a=open(),b=open();a=advance(a,190);b=advance(b,190);expect(a).toEqual(b);const count=a.incidents.length;a=act(a,{type:'STEP'});expect(a.incidents.length).toBe(count);});
 it('tắt trộm và gian lận được tôn trọng nhiều ngày, ngày đầu chỉ nhẹ',()=>{let s=createGame({seed:492});s=act(s,{type:'SETTINGS',patch:{theft:false,fraud:false,eventFrequency:'high'}});for(let day=0;day<5;day++){s=act(s,{type:'OPEN'});for(let t=0;t<660;t+=60){s=advance(s,60);for(const i of s.incidents.filter(i=>i.stage!=='resolved')){for(const e of i.evidence)s=act(s,{type:'INVESTIGATE',incidentId:i.id,evidenceId:e.id});s=act(s,{type:'RESOLVE',incidentId:i.id,choiceId:i.choices[0].id});}}s=act(s,{type:'CLOSE'});s=act(s,{type:'CLOSE'});s=act(s,{type:'NEXT_DAY'});}expect(s.incidents.some(i=>i.type==='theft'||i.type==='fraud')).toBe(false);expect(s.incidents.filter(i=>i.day===1).every(i=>i.severity!=='serious')).toBe(true);});
 it('không đủ bằng chứng thì chưa cho kết luận; sự cố đã giải quyết không phát tác động hai lần',()=>{let s=createGame();s.incidents.push(incidentFixture());s=act(s,{type:'RESOLVE',incidentId:'test-incident',choiceId:'verify'});expect(s.incidents[0].resolving).toBeUndefined();for(const e of s.incidents[0].evidence)s=act(s,{type:'INVESTIGATE',incidentId:'test-incident',evidenceId:e.id});s=act(s,{type:'RESOLVE',incidentId:'test-incident',choiceId:'verify'});s=advance(s,5);expect(s.incidents[0].stage).toBe('resolved');const rep=s.reputation;s=act(s,{type:'RESOLVE',incidentId:'test-incident',choiceId:'verify'});s=advance(s,5);expect(s.reputation).toBe(rep);});
 it('sai số vô ý không tự động gán gian lận; buộc tội thiếu căn cứ có hậu quả',()=>{let s=createGame();s=act(s,{type:'HIRE',staffId:'lan'});s.incidents.push(incidentFixture('count','miscount'));const spirit=s.staff[0].satisfaction;s=act(s,{type:'RESOLVE',incidentId:'test-incident',choiceId:'accuse'});s=advance(s,5);expect(s.incidents[0].cause).toBe('miscount');expect(s.incidents[0].outcome).toContain('không phải gian lận');expect(s.staff[0].satisfaction).toBeLessThan(spirit);});
 it('đối soát minigame cần khớp kho thật, không phát thưởng tiền',()=>{let s=createGame(),cash=s.cash;s=act(s,{type:'AUDIT',kind:'count',inventoryCount:[{ingredient:'milk',quantity:1}]});expect(s.flags.audit).not.toBe(true);s=act(s,{type:'AUDIT',kind:'count',inventoryCount:[{ingredient:'milk',quantity:stock(s,'milk')}]});expect(s.flags.audit).toBe(true);expect(s.cash).toBe(cash);});
 it('thất thoát tiền có dấu vết, bảo hiểm bù đúng và không trừ / bồi thường hai lần',()=>{let found:GameState|undefined;for(let seed=1;seed<200;seed++){const s=open();s.day=2;s.seed=(seed*1103515245)>>>0;s.hygiene=100;s.inventory=[];s.flags.marketUntil=4;s.nextIncidentAt=0;for(const c of s.cats){c.energy=100;c.health=100;}const ordered=act(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte',kind:'table'});ordered.seed=(seed*1103515245)>>>0;maybeIncident(ordered);if(ordered.incidents[0]?.type==='theft'){found=ordered;break;}}expect(found).toBeDefined();let s=found!;expect(s.transactions.filter(t=>t.category==='loss')).toHaveLength(1);const loss=s.incidents[0];expect(s.cash).toBe(838000);s=act(s,{type:'INSURE'});for(const e of loss.evidence)s=act(s,{type:'INVESTIGATE',incidentId:loss.id,evidenceId:e.id});s=act(s,{type:'RESOLVE',incidentId:loss.id,choiceId:'verify'});s=advance(s,25);expect(s.transactions.filter(t=>t.category==='loss')).toHaveLength(1);expect(s.transactions.filter(t=>t.category==='insurance'&&t.expense<0)).toHaveLength(1);expect(s.transactions.find(t=>t.id===`insurance:${loss.id}`)!.cash).toBe(8400);const cash=s.cash;s=act(s,{type:'RESOLVE',incidentId:loss.id,choiceId:'verify'});s=advance(s,25);expect(s.cash).toBe(cash);expect(reportDay(s).netRevenue).toBe(0);expect(reportDay(s).profit).toBe(-12000-12000+8400);});
 it('thất thoát kho do tủ lạnh dùng hàng có thật, COGS một lần và mọi sự cố nghiêm trọng có lối phục hồi',()=>{let found:GameState|undefined;for(let seed=1;seed<200;seed++){const s=open();s.day=2;s.seed=(seed*1103515245)>>>0;s.hygiene=100;s.flags.marketUntil=4;s.nextIncidentAt=0;s.inventory=s.inventory.filter(b=>b.ingredient==='milk');s.inventory[0].quantity=100;s.equipment.find(e=>e.id==='fridge')!.durability=10;for(const c of s.cats){c.energy=100;c.health=100;}maybeIncident(s);if(s.incidents[0]?.type==='fridge'){found=s;break;}}expect(found).toBeDefined();let s=found!,id=s.incidents[0].id;expect(stock(s,'milk')).toBe(40);const cost=reportDay(s).cogs;expect(cost).toBe(60*35);expect(s.incidents[0].choices.some(c=>!c.requiresEvidence&&c.cost===0)).toBe(true);s=act(s,{type:'RESOLVE',incidentId:id,choiceId:'repair'});s=advance(s,30);s=act(s,{type:'RESOLVE',incidentId:id,choiceId:'repair'});expect(stock(s,'milk')).toBe(40);expect(reportDay(s).cogs).toBe(cost);expect(s.equipment.find(e=>e.id==='fridge')!.durability).toBe(90);});
 it('workshop dùng kho một lần, chạy40s rồi thu phí thật, không nhận hai lần',()=>{let s=open();s.xp=80;s.level=2;s=act(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});s=act(s,{type:'ORDER',customerId:'an',recipeId:'houjicha-latte'});const tea=stock(s,'matcha');s=act(s,{type:'WORKSHOP'});expect(stock(s,'matcha')).toBe(tea-8);const cash=s.cash;s=advance(s,39);expect(s.cash).toBe(cash);s=advance(s,1);expect(s.cash).toBe(cash+40000);s=act(s,{type:'WORKSHOP'});expect(stock(s,'matcha')).toBe(tea-8);expect(s.transactions.filter(t=>t.category==='workshop-sales')).toHaveLength(1);});
 it('vòng chơi mới hoàn thành một ngày và báo cáo không dùng dữ liệu ngẫu nhiên',()=>{let s=served();s=advance(s,660);if(s.phase==='closing')s=advance(s,30);expect(s.phase).toBe('after');expect(s.reports).toHaveLength(1);expect(s.reports[0].served).toBe(1);expect(s.reports[0].netRevenue).toBe(s.transactions.filter(t=>t.day===1).reduce((n,t)=>n+t.revenue,0));expect(activeOrders(s)).toHaveLength(0);});
});


