import {describe,it,expect} from 'vitest';
import {createGame,reduceGame,stock,reportDay,capacity,recipes,scoreDrink,customers,incidentTemplates} from '../src/domain';
import {triggerIncident} from '../src/domain/events';
import {post} from '../src/domain/finance';
import {exportGame,importGame,validateGame} from '../src/persistence';
import type {GameState,GameAction} from '../src/domain';
const act=(s:GameState,a:GameAction)=>reduceGame(s,a);
function step(s:GameState,n:number):GameState{for(let k=0;k<n;k+=60)s=act(s,{type:'STEP',seconds:Math.min(60,n-k)});return s;}
function game(day=2):GameState{let s=createGame();for(let n=1;n<day;n++){s=act(s,{type:'OPEN'});s=act(s,{type:'CLOSE'});s=act(s,{type:'NEXT_DAY'});}s=act(s,{type:'OPEN'});s.nextIncidentAt=s.clock+100000;s.nextCustomerAt=s.clock+100000;return s;}
function order(s:GameState,customerId='linh',recipeId='matcha-latte'):GameState{return act(s,{type:'ORDER',customerId,recipeId,kind:'table'});}
function serve(s:GameState,bad=false):GameState{const o=s.orders.at(-1)!;s=act(s,{type:'START_DRINK',orderId:o.id,formula:bad?{...o.requested,sugar:55,dissolution:0,presentation:30}:o.requested});s=act(s,{type:'FINISH_DRINK',orderId:o.id,technique:bad?0:100});return act(s,{type:'SERVE',orderId:o.id});}
function start(s:GameState,type:string):GameState{const incident=triggerIncident(s,type);expect(incident,`eligibility ${type}`).not.toBeNull();return s;}
function resolve(s:GameState,choiceId:string):GameState{const i=s.incidents.at(-1)!;for(const e of i.evidence)s=act(s,{type:'INVESTIGATE',incidentId:i.id,evidenceId:e.id});s=act(s,{type:'RESOLVE',incidentId:i.id,choiceId});const time=s.incidents.at(-1)!.resolving?.remaining??0;expect(time).toBeGreaterThan(0);return step(s,time);}

describe('gia đình sự kiện liên kết dữ liệu',()=>{
 it('52 mẫu riêng biệt, mỗi biến cố nghiêm trọng có lựa chọn phục hồi miễn phí',()=>{expect(incidentTemplates.length).toBeGreaterThanOrEqual(50);expect(new Set(incidentTemplates.map(t=>t.type)).size).toBe(incidentTemplates.length);for(const type of ['stockloss','decorloss','staffstock','unpaidmeal','fridge','theft','fraud']){const t=incidentTemplates.find(t=>t.type===type)!;expect(t.choices.some(c=>c.cost===0&&!c.requiresEvidence)).toBe(true);}});
 it('đến trễ không có giờ công giả, đổi / nghỉ ca bàn giao món đã pha',()=>{let s=act(game(),{type:'HIRE',staffId:'lan'});s=start(s,'late');expect(s.staff[0].onShift).toBe(false);s=resolve(s,'cover');expect(s.staff[0].onShift).toBe(true);expect(s.staff[0].secondsWorked).toBe(0);s=step(s,110);s=order(s);s=act(s,{type:'ASSIGN',staffId:'lan',task:'drink',targetId:s.orders.at(-1)!.id});const milk=stock(s,'milk');s=start(s,'emergency');s=resolve(s,'leave');expect(s.staff[0].onShift).toBe(false);expect(s.staff[0].taskId).toBeUndefined();expect(s.tasks.at(-1)!.status).toBe('handed-over');expect(s.orders.at(-1)!.draft).toBeDefined();expect(stock(s,'milk')).toBe(milk);expect(importGame(exportGame(s)).staff[0].onShift).toBe(false);});
 it('hướng dẫn người mới đòi hỏi tác vụ thật; đề nghị nơi khác có thương lượng hoặc thời hạn nghỉ',()=>{let s=act(game(4),{type:'HIRE',staffId:'lan'});s=act(s,{type:'HIRE',staffId:'quang'});expect(triggerIncident(s,'newcomer')).toBeNull();s.staff[0].experience=10;s=start(s,'newcomer');const skill=s.staff[5].skill;s=resolve(s,'teach');expect(s.staff[5].skill).toBe(skill+5);expect(s.staff[5].trained).toBe(1);s=start(s,'poaching');expect(s.staff[0].noticeDay).toBe(6);const salary=s.staff[0].salary;s=resolve(s,'negotiate');expect(s.staff[0].salary).toBe(Math.round(salary*1.1));expect(s.staff[0].noticeDay).toBeUndefined();expect(s.staff[0].former).toBe(false);});
 it('nhận thông báo nghỉ đủ hai ngày rồi mới quyết toán, hồ sơ giữ lại',()=>{let s=act(game(4),{type:'HIRE',staffId:'lan'});s.staff[0].experience=10;s=start(s,'poaching');s=resolve(s,'accept');for(let d=0;d<2;d++){s=act(s,{type:'CLOSE'});s=act(s,{type:'CLOSE'});s=act(s,{type:'NEXT_DAY'});if(d===0)s=act(s,{type:'OPEN'});}expect(s.day).toBe(6);expect(s.staff[0].former).toBe(true);expect(s.staff[0].hired).toBe(false);expect(s.transactions.filter(t=>t.id.startsWith('salary-fire:lan:6'))).toHaveLength(1);const cash=s.cash;s=act(s,{type:'FIRE',staffId:'lan',confirm:true,reason:'bấm lại'});expect(s.cash).toBe(cash);validateGame(s);});
 it('khách đổi yêu cầu hủy món có chi phí thật; không lấy lại sữa đã rót',()=>{let s=order(game());const id=s.orders.at(-1)!.id;s=act(s,{type:'START_DRINK',orderId:id});const cost=reportDay(s).cogs,tea=stock(s,'matcha');s=start(s,'change');s=resolve(s,'remake');expect(s.orders.at(-1)!.status).toBe('waiting');expect(s.orders.at(-1)!.requested.temperature).toBe(55);expect(reportDay(s).cogs).toBe(cost);expect(reportDay(s).waste.length).toBeGreaterThan(0);s=act(s,{type:'START_DRINK',orderId:id});expect(stock(s,'matcha')).toBe(tea-3);expect(reportDay(s).cogs).toBeGreaterThan(cost);});
 it('hoàn có cơ sở dùng đúng phiếu; thiếu cơ sở không bịa hoàn tiền; thuế sau hoàn vẫn 5%',()=>{let s=serve(order(game()),true);const id=s.orders.at(-1)!.id,price=s.orders.at(-1)!.price;expect(s.orders.at(-1)!.score!.total).toBeLessThan(70);s=start(s,'validrefund');s=act(s,{type:'CLOSE'});expect(s.phase).toBe('after');s=resolve(s,'refund');expect(s.orders.find(o=>o.id===id)!.refunded).toBe(Math.round(price/2));expect(reportDay(s).tax).toBe(Math.round(reportDay(s).netRevenue*.05));validateGame(s);const cash=s.cash;s=act(s,{type:'RESOLVE',incidentId:s.incidents.at(-1)!.id,choiceId:'refund'});expect(s.cash).toBe(cash);let good=serve(order(game()));good=start(good,'invalidrefund');const goodCash=good.cash;good=resolve(good,'verify');expect(good.cash).toBe(goodCash);expect(good.orders.at(-1)!.refunded).toBe(0);});
 it('khách chiếm bàn đã trả vẫn hiện diện; nhắc nội quy giải phóng chỗ và không thu lại',()=>{let s=serve(order(game()));for(const id of ['an','bao','vy'])s=order(s,id,id==='an'||id==='bao'?'houjicha-latte':'sencha-lemon');s=start(s,'overstay');const customerOrder=s.orders[0],cash=s.cash;s=resolve(s,'remind');expect(s.orders.find(o=>o.id===customerOrder.id)!.seatReleased).toBe(true);expect(s.cash).toBe(cash);});
 it('giao thiếu dùng số lượng thực nhận và bù chi phí đúng một lần',()=>{let s=act(game(),{type:'BUY_INGREDIENT',ingredient:'matcha',quantity:100,supplierId:'local'});s=start(s,'deliveryshort');const d=s.deliveries.at(-1)!;expect(d.expectedQuantity).toBe(100);expect(d.quantity).toBe(90);expect(reportDay(s).operating).toBe(1800);s=resolve(s,'claim');expect(reportDay(s).operating).toBe(0);s=step(s,6);expect(stock(s,'matcha')).toBe(190);expect(s.transactions.filter(t=>t.id===`short-refund:${d.id}`)).toHaveLength(1);validateGame(s);});
 it('cách ly chặn nguyên liệu; chất lượng đã xác minh còn thấp và ảnh hưởng điểm',()=>{let s=act(game(),{type:'BUY_INGREDIENT',ingredient:'milk',quantity:100,supplierId:'budget'});s=step(s,65);const before=stock(s,'milk');s=start(s,'quarantine');expect(stock(s,'milk')).toBe(before-100);expect(s.deliveries.at(-1)!.quality).toBe(55);s=resolve(s,'verify');expect(stock(s,'milk')).toBe(before);const f=recipes[0].formula;expect(scoreDrink(f,{requested:f},customers[0],100,98).requirement).toBeGreaterThan(scoreDrink(f,{requested:f},customers[0],100,55).requirement);validateGame(s);});
 it('mất đồ và trà tương ứng tồn tại, không trừ lại hoặc ghi doanh thu mất cơ hội',()=>{let s=order(game(3));s=act(s,{type:'BUY_FURNITURE',kind:'plant'});const f=s.storage[0];s=act(s,{type:'PLACE_FURNITURE',furnitureId:f.id,x:1,y:5,rotation:0});s=start(s,'decorloss');expect(s.furniture.some(x=>x.id===f.id)).toBe(false);const cash=s.cash;s=resolve(s,'record');expect(s.cash).toBe(cash);expect(s.transactions.filter(t=>t.category==='asset-loss')).toHaveLength(1);s=start(s,'stockloss');const tea=stock(s,'matcha');s=resolve(s,'record');expect(stock(s,'matcha')).toBe(tea);expect(reportDay(s).netRevenue).toBe(0);validateGame(s);});
 it('bàn hỏng giảm sức chứa, tự sửa theo thời gian phục hồi; rác và mèo cửa có hậu quả thật',()=>{let s=order(game(3)),seats=capacity(s);s=start(s,'damage');expect(capacity(s)).toBe(seats-2);s=resolve(s,'selfrepair');expect(capacity(s)).toBe(seats);s.flags.trash=5;s=start(s,'trash');expect(s.flags.trashFull).toBe(true);s=resolve(s,'clear');expect(s.flags.trash).toBe(0);expect(s.flags.trashFull).toBe(false);s.equipment.find(e=>e.id==='catgate')!.durability=40;s=start(s,'catescape');expect(s.cats[0].activity).toBe('nấp gần cửa');s=resolve(s,'lure');expect(s.flags['escaped:matcha']).toBe(false);expect(s.cats[0].trust).toBe(33);});
 it('thị trường báo giá trước và thay nhu cầu có hạn, không đổi lô đã mua',()=>{let s=game(3);const oldCost=s.inventory.find(b=>b.ingredient==='milk')!.unitCost;s=start(s,'market');s=resolve(s,'backup');s=act(s,{type:'BUY_INGREDIENT',ingredient:'milk',quantity:10,supplierId:'local'});expect(s.deliveries.at(-1)!.unitCost).toBe(35);s=start(s,'construction');s=resolve(s,'sign');s=act(s,{type:'BUY_INGREDIENT',ingredient:'milk',quantity:10,supplierId:'local'});expect(s.deliveries.at(-1)!.remaining).toBe(48);expect(s.inventory.find(b=>b.ingredient==='milk')!.unitCost).toBe(oldCost);s=start(s,'trend');s=resolve(s,'adapt');expect(s.flags.trendTea).toBe('houjicha');expect(s.flags.trendUntil).toBe(s.day+2);});
 it('đơn nhóm chỉ mở từ khách có lịch sử thật, không tự sinh doanh thu',()=>{let s=order(game());expect(triggerIncident(s,'bulk')).toBeNull();s.customers.linh.visits=3;s=start(s,'bulk');const cash=s.cash,orders=s.orders.length;s=resolve(s,'accept');expect(s.orders.length).toBe(orders+3);expect(s.cash).toBe(cash);expect(reportDay(s).revenue).toBe(0);expect(s.orders.filter(o=>o.kind==='delivery')).toHaveLength(3);});
 it('công thức riêng nổi tiếng dựa vào 3 món đã bán và chất lượng; hỗ trợ là vốn, không phải doanh thu',()=>{let s=game();s=act(s,{type:'SAVE_RECIPE',recipe:{...recipes[0],id:'custom',name:'Lá nhà',custom:true}});const recipeId=s.recipes.at(-1)!.id;s=act(s,{type:'MENU',recipeId,enabled:true});expect(triggerIncident(s,'viralrecipe')).toBeNull();for(const id of ['linh','an','bao'])s=serve(order(s,id,recipeId));s=start(s,'viralrecipe');s=resolve(s,'feature');expect(s.flags.viralRecipe).toBe(recipeId);expect(s.flags.viralUntil).toBe(s.day+2);const before=reportDay(s).netRevenue;s.incidents.push({id:'old-loss',type:'fixture',title:'Hồ sơ cũ',description:'Đã ghi',sign:'Sổ',stage:'resolved',createdAt:s.clock,day:s.day,severity:'serious',participants:[],evidence:[],choices:[{id:'record',label:'Đã ghi',description:'Đã ghi',cost:0,duration:1}],cause:'accident',lossCash:0,lossQuantity:0});s.customers.linh.visits=3;s=start(s,'aid');const cash=s.cash;s=resolve(s,'accept');expect(s.cash).toBe(cash+15000);expect(reportDay(s).netRevenue).toBe(before);expect(s.transactions.at(-1)!.category).toBe('community-capital');validateGame(s);});
 it('kho và nhân sự đã nghỉ không tạo sự cố tương ứng; tắt sự kiện áp dụng cả mẫu mới',()=>{let s=game(4);s.settings.theft=false;s.settings.fraud=false;s.inventory=s.inventory.filter(b=>b.ingredient!=='matcha'&&b.ingredient!=='houjicha');expect(triggerIncident(s,'stockloss')).toBeNull();expect(triggerIncident(s,'staffstock')).toBeNull();expect(triggerIncident(s,'decorloss')).toBeNull();s=act(s,{type:'HIRE',staffId:'lan'});s=act(s,{type:'FIRE',staffId:'lan',reason:'Kết ca',confirm:true});expect(triggerIncident(s,'late')).toBeNull();expect(triggerIncident(s,'poaching')).toBeNull();});
});
describe('nợ đến hạn và khả năng phục hồi',()=>{
 it('gốc và lãi đến đúng ngày, gốc quá hạn vào phải trả, trả hóa đơn không ghi chi phí lần hai',()=>{let s=createGame();s=act(s,{type:'LOAN',amount:100000});post(s,{id:'fixture-cost',label:'Chi phí thử khả năng phục hồi',category:'test-operation',cash:-s.cash,expense:s.cash});for(let d=0;d<3;d++){s=act(s,{type:'OPEN'});s=act(s,{type:'CLOSE'});if(d<2)s=act(s,{type:'NEXT_DAY'});}const loan=s.loans[0],bill=s.payables.find(p=>p.loanId===loan.id)!;expect(loan.remaining).toBe(100000);expect(loan.arrears).toBe(25000);expect(loan.nextDay).toBe(5);expect(bill.amount).toBe(25000);expect(s.transactions.filter(t=>t.id.startsWith('interest:'))).toHaveLength(1);expect(s.transactions.find(t=>t.category==='loan-principal-due')!.expense).toBe(0);s=act(s,{type:'LOAN',amount:100000});const operating=reportDay(s).operating;s=act(s,{type:'PAY_BILL',payableId:bill.id});expect(s.loans[0].remaining).toBe(75000);expect(s.loans[0].arrears).toBe(0);expect(reportDay(s).operating).toBe(operating);const cash=s.cash;s=act(s,{type:'PAY_BILL',payableId:bill.id});expect(s.cash).toBe(cash);validateGame(s);});
 it('kinh doanh cảnh báo 3 ngày trước tạm ngừng, khoản vay phục hồi được mở lại; thư giãn hỗ trợ một lần',()=>{let s=createGame({mode:'business'});post(s,{id:'fixture-cost',label:'Chi phí có dấu vết',category:'test-operation',cash:-s.cash,expense:s.cash});for(let d=0;d<3;d++){s=act(s,{type:'OPEN'});s=act(s,{type:'CLOSE'});expect(s.flags.warningStreak).toBe(d+1);if(d<2)s=act(s,{type:'NEXT_DAY'});}expect(s.flags.businessFailed).toBe(true);const day=s.day;s=act(s,{type:'NEXT_DAY'});expect(s.day).toBe(day);s=act(s,{type:'LOAN',amount:100000});expect(s.flags.businessFailed).toBe(false);s=act(s,{type:'NEXT_DAY'});expect(s.day).toBe(day+1);validateGame(s);let relaxed=createGame();post(relaxed,{id:'fixture-cost',label:'Chi phí có dấu vết',category:'test-operation',cash:-relaxed.cash,expense:relaxed.cash});relaxed=act(relaxed,{type:'OPEN'});relaxed=act(relaxed,{type:'CLOSE'});const reward=relaxed.missions.find(m=>m.id.startsWith('recovery-'))!;relaxed=act(relaxed,{type:'CLAIM_MISSION',missionId:reward.id});const cash=relaxed.cash;relaxed=act(relaxed,{type:'CLAIM_MISSION',missionId:reward.id});expect(relaxed.cash).toBe(cash);expect(reportDay(relaxed).revenue).toBe(0);expect(relaxed.flags.businessFailed).not.toBe(true);});
 it('bản v3 cũ bổ sung traits nhưng từ chối traits giả / liên kết lô không tồn tại',()=>{const legacy=JSON.parse(JSON.stringify(game()));delete legacy.staff[0].traits;expect(importGame(JSON.stringify(legacy)).staff[0].traits).toEqual(createGame().staff[0].traits);legacy.staff[0].traits={responsibility:500,motivation:80,attachment:70};expect(()=>importGame(JSON.stringify(legacy))).toThrow(/đặc tính/);});
});
