import {describe,it,expect,beforeEach} from 'vitest';
import 'fake-indexeddb/auto';
import {createGame,reduceGame,stock} from '../src/domain';
import {exportGame,importGame,saveGame,loadGame,clearGame,validateGame,saveSettings,loadSettings} from '../src/persistence';
beforeEach(async()=>{await clearGame();});
describe('bản lưu cục bộ có phiên bản và đối soát',()=>{
 it('xuất / nhập giữ đơn đã trả, kho, seed và không thu tiền lần nữa',()=>{let s=reduceGame(createGame(),{type:'OPEN'});s=reduceGame(s,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});const id=s.orders[0].id;s=reduceGame(s,{type:'START_DRINK',orderId:id});s=reduceGame(s,{type:'FINISH_DRINK',orderId:id,technique:92});s=reduceGame(s,{type:'SERVE',orderId:id});const loaded=importGame(exportGame(s));expect(loaded).toEqual(s);expect(reduceGame(loaded,{type:'SERVE',orderId:id}).cash).toBe(s.cash);expect(stock(loaded,'matcha')).toBe(stock(s,'matcha'));});
 it('đóng ngày, trang trí và ngày mới đều lưu được cùng báo cáo thật',async()=>{let s=reduceGame(createGame(),{type:'OPEN'});s=reduceGame(s,{type:'CLOSE'});s=reduceGame(s,{type:'BUY_FURNITURE',kind:'plant'});s=reduceGame(s,{type:'PLACE_FURNITURE',furnitureId:s.storage[0].id,x:1,y:5,rotation:0});s=reduceGame(s,{type:'NEXT_DAY'});await saveGame(s);expect(await loadGame()).toEqual(s);});
 it('save nối tiếp có dự phòng, bản chính hỏng phục hồi bản hợp lệ trước đó',async()=>{const a=createGame(),b=reduceGame(a,{type:'BUY_FURNITURE',kind:'plant'});await saveGame(a);await saveGame(b);const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('miu-matcha-local',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await new Promise<void>((resolve,reject)=>{const tx=db.transaction('saves','readwrite');tx.objectStore('saves').put('{corrupt','current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});const recovered=await loadGame();expect(recovered!.cash).toBe(a.cash);expect(recovered!.lastMessage).toContain('dự phòng');});
 it('phát hiện sửa dữ liệu trong phong bì mà không cập nhật checksum',()=>{const parsed=JSON.parse(exportGame(createGame()));parsed.payload.cash+=100000;expect(()=>importGame(JSON.stringify(parsed))).toThrow(/kiểm tra/);});
 it('không nhận kho âm, giao dịch trùng hoặc tiền không khớp sổ ngay cả với JSON thô',()=>{const a=createGame();a.inventory[0].quantity=-1;expect(()=>importGame(JSON.stringify(a))).toThrow(/lô/);const b=createGame();b.cash++;expect(()=>validateGame(b)).toThrow(/tiền mặt/);let c=reduceGame(createGame(),{type:'BUY_FURNITURE',kind:'plant'});c.transactions.push({...c.transactions[0]});expect(()=>validateGame(c)).toThrow(/trùng/);});
 it('không nhận nhân viên nghỉ vẫn làm, phiếu trả không có giao dịch hoặc vị trí chắn cửa',()=>{const a=createGame();a.staff[0].former=true;a.staff[0].hired=true;expect(()=>validateGame(a)).toThrow(/nghỉ/);const b=reduceGame(createGame(),{type:'OPEN'});const ordered=reduceGame(b,{type:'ORDER',customerId:'linh',recipeId:'matcha-latte'});ordered.orders[0].paid=true;expect(()=>validateGame(ordered)).toThrow(/thanh toán/);const c=createGame();c.furniture[0].x=7;c.furniture[0].y=10;expect(()=>validateGame(c)).toThrow(/chặn cửa/);});
 it('migration phiên bản2 giữ tiền / seed và bổ sung trường mặc định, không nhận bản tương lai',()=>{const legacy=JSON.parse(JSON.stringify(createGame()));legacy.version=2;delete legacy.reserve;delete legacy.insured;delete legacy.insuranceClaimDay;delete legacy.avatar;delete legacy.settings.reducedMotion;const migrated=importGame(JSON.stringify(legacy));expect(migrated.version).toBe(3);expect(migrated.cash).toBe(legacy.cash);expect(migrated.seed).toBe(legacy.seed);expect(migrated.reserve).toBe(0);expect(migrated.settings.reducedMotion).toBe(false);legacy.version=99;expect(()=>importGame(JSON.stringify(legacy))).toThrow(/phiên bản/);});
 it('cài đặt được lưu riêng và chơi mới không xóa âm lượng / tiếp cận',async()=>{const settings={...createGame().settings,music:.1,reducedMotion:true};await saveSettings(settings);await saveGame(createGame());await clearGame();expect(await loadGame()).toBeNull();expect(await loadSettings()).toEqual(settings);});
 it('hồ sơ vụ việc, phần thưởng và tác vụ giữ trạng thái qua tải',()=>{let s=reduceGame(createGame(),{type:'HIRE',staffId:'khoa'});s=reduceGame(s,{type:'ASSIGN',staffId:'khoa',task:'cat',targetId:'matcha'});const restored=importGame(exportGame(s));expect(restored.tasks).toEqual(s.tasks);expect(restored.staff).toEqual(s.staff);const next=reduceGame(restored,{type:'STEP',seconds:18});expect(stock(next,'catfood')).toBe(stock(restored,'catfood'));});
});
