import { createGame, defaultSettings, ingredients, furniture, customers, staff as staffCatalog, cats as catCatalog, equipment as equipmentCatalog, suppliers, validFormula, reportDay, canPlace } from './domain';
import type { GameState, Settings } from './domain';

const DB_NAME='miu-matcha-local', STORE='saves', CURRENT='current', BACKUP='backup', SETTINGS='settings';
let dbPromise:Promise<IDBDatabase>|undefined;
const memory=new Map<string,string>();
function checksum(text:string):string {let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return (hash>>>0).toString(16).padStart(8,'0');}
function assert(ok:unknown,message:string):asserts ok {if(!ok)throw new Error('Bản lưu không hợp lệ: '+message);}
const integer=(n:unknown,min=0,max=1_000_000_000):n is number=>typeof n==='number'&&Number.isSafeInteger(n)&&n>=min&&n<=max;
const number=(n:unknown,min=0,max=100):n is number=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max;
const string=(n:unknown,max=1000):n is string=>typeof n==='string'&&n.length<=max;
const plain=(a:unknown):a is Record<string,unknown>=>!!a&&typeof a==='object'&&!Array.isArray(a)&&(Object.getPrototypeOf(a)===Object.prototype||Object.getPrototypeOf(a)===null);
function list(a:unknown,max=10000):asserts a is Record<string,unknown>[] {assert(Array.isArray(a)&&a.length<=max&&a.every(plain),'danh sách dữ liệu bị hỏng');}
function ids(a:Record<string,unknown>[],kind:string):Set<string> {const set=new Set<string>();for(const v of a){assert(string(v.id,180)&&v.id.length>0,kind+' thiếu mã');assert(!set.has(v.id),kind+' có mã trùng');set.add(v.id);}return set;}
function noUnsafeKeys(a:unknown,depth=0):void {assert(depth<35,'dữ liệu lồng quá sâu');if(a&&typeof a==='object')for(const [key,value] of Object.entries(a)){assert(!['__proto__','constructor','prototype'].includes(key),'khóa đối tượng không an toàn');noUnsafeKeys(value,depth+1);}}
export function validateGame(value:unknown):GameState {
 assert(plain(value),'không phải đối tượng');noUnsafeKeys(value);const s=value;
 assert(s.version===3,'phiên bản chưa hỗ trợ');assert(string(s.id,100)&&s.id.length>0,'mã quán');assert(integer(s.sequence)&&integer(s.seed,1,4294967295),'seed / mã tác vụ');
 for(const key of ['day','level'])assert(integer(s[key],1,key==='level'?6:10000),key);
 for(const key of ['clock','elapsed','closingElapsed','cash','startCash','reserve','xp','tutorial','nextCustomerAt','nextIncidentAt','insuranceClaimDay'])assert(integer(s[key]),key);
 assert(integer(s.dayDuration,600,900),'thời gian ngày');assert(['preparation','open','closing','after'].includes(String(s.phase)),'giai đoạn');assert(['relax','business'].includes(String(s.mode)),'chế độ');assert(['sun','rain','cool'].includes(String(s.weather)),'thời tiết');
 assert(typeof s.paused==='boolean'&&typeof s.insured==='boolean'&&string(s.lastMessage),'cờ / thông báo');assert(number(s.reputation)&&number(s.hygiene),'chỉ số quán');assert(plain(s.avatar)&&integer(s.avatar.hair,0,5)&&integer(s.avatar.skin,0,4)&&integer(s.avatar.outfit,0,4),'diện mạo');
 assert(plain(s.settings),'cài đặt');const settings=s.settings;assert(number(settings.music,0,1)&&number(settings.effects,0,1)&&integer(settings.dayDuration,600,900)&&number(settings.taxRate,0,.15),'cài đặt số');assert(['low','medium','high'].includes(String(settings.eventFrequency)),'tần suất sự cố');for(const k of ['reducedMotion','theft','fraud','tutorial'])assert(typeof settings[k]==='boolean','cài đặt '+k);
 assert(plain(s.flags)&&Object.values(s.flags).every(v=>typeof v==='boolean'||string(v)||number(v,-1e9,1e9)),'cờ câu chuyện');
 const requiredLists=['inventory','orders','recipes','cats','staff','tasks','baking','cakes','deliveries','equipment','furniture','storage','transactions','payables','loans','reports','incidents','journal','album','missions'];for(const key of requiredLists){list(s[key]);if(key!=='reports')ids(s[key] as Record<string,unknown>[],key);}
 // Reports are identified by day, not id: checked independently below.
 const state=s as unknown as GameState;
 assert(state.recipes.length<=40&&state.cats.length===6&&state.staff.length===6&&state.equipment.length===7,'kích thước danh mục');
 const ingredientIds=new Set(ingredients.map(i=>i.id));for(const b of state.inventory){assert(ingredientIds.has(b.ingredient)&&integer(b.quantity,1,1000000)&&integer(b.unitCost)&&integer(b.expiresDay,1,10050)&&number(b.quality),'lô nguyên liệu');assert(b.quarantined===undefined||typeof b.quarantined==='boolean','cách ly lô');}
 for(const r of state.recipes){assert(string(r.name,48)&&r.name.trim().length>0&&validFormula(r.formula)&&integer(r.price,10000,100000)&&integer(r.level,1,6)&&integer(r.time,1,180),'công thức');}
 assert(Array.isArray(state.menu)&&state.menu.length<=40&&new Set(state.menu).size===state.menu.length&&state.menu.every(id=>state.recipes.some(r=>r.id===id)),'menu');
 const orderIds=new Set(state.orders.map(o=>o.id));for(const o of state.orders){assert(customers.some(c=>c.id===o.customerId)&&state.recipes.some(r=>r.id===o.recipeId)&&validFormula(o.requested),'tham chiếu đơn');assert(['waiting','making','ready','served','left','discarded'].includes(o.status)&&['table','takeaway','delivery','combo'].includes(o.kind)&&typeof o.paid==='boolean','trạng thái đơn');assert(integer(o.price,0,150000)&&integer(o.createdAt,0,state.clock)&&number(o.remaining,-1000,1000)&&integer(o.refunded,0,o.price),'giá / thời gian đơn');assert(o.status!=='served'||o.paid,'đơn đã giao chưa ghi thanh toán');if(o.draft)assert(validFormula(o.draft.formula)&&integer(o.draft.cost)&&number(o.draft.technique)&&Array.isArray(o.draft.steps),'món đang pha');if(o.score){for(const [key,max] of [['requirement',30],['taste',30],['technique',20],['temperature',10],['presentation',10]] as const)assert(integer(o.score[key],0,max),'điểm món');assert(o.score.total===o.score.requirement+o.score.taste+o.score.technique+o.score.temperature+o.score.presentation&&string(o.score.feedback),'tổng điểm món');}}
 for(const c of state.cats){assert(catCatalog.some(a=>a.id===c.id)&&typeof c.unlocked==='boolean'&&string(c.expression)&&string(c.activity),'mèo');for(const k of ['hunger','joy','energy','cleanliness','trust','health'] as const)assert(number(c[k]),'chỉ số mèo');for(const k of ['cooldownUntil','interactions','gamesToday','restingUntil'] as const)assert(integer(c[k]),'giới hạn mèo');assert(c.gamesToday<=3,'lượt chơi mèo');}
 for(const w of state.staff){assert(staffCatalog.some(a=>a.id===w.id)&&['barista','baker','cashier','carer','manager'].includes(w.role)&&integer(w.salary,1000,1000000)&&number(w.speed,.1,5),'nhân viên');for(const k of ['skill','communication','energy','satisfaction'] as const)assert(number(w[k]),'chỉ số nhân viên');for(const k of ['experience','secondsWorked','salaryPaidDay','trained','warnings'] as const)assert(integer(w[k]),'hồ sơ nhân viên');for(const k of ['hired','former','onShift','sensitiveAllowed'] as const)assert(typeof w[k]==='boolean','cờ nhân viên');assert(!(w.former&&(w.hired||w.onShift)),'nhân viên đã nghỉ còn làm');assert(Array.isArray(w.history)&&w.history.every(t=>string(t)),'lịch sử nhân viên');assert(plain(w.traits)&&number(w.traits.responsibility)&&number(w.traits.motivation)&&number(w.traits.attachment),'đặc tính nội bộ nhân viên');if(w.noticeDay!==undefined)assert(integer(w.noticeDay,1,10050),'thời hạn báo nghỉ');}
 const workingTargets=new Set<string>();for(const t of state.tasks){assert(state.staff.some(w=>w.id===t.workerId)&&['drink','bake','serve','cat','clean','inspect'].includes(t.type)&&['working','done','handed-over'].includes(t.status)&&typeof t.claimed==='boolean'&&integer(t.duration,1,300)&&number(t.remaining,-1,300),'tác vụ');assert(t.status!=='working'||!t.claimed,'tác vụ đang làm đã nhận kết quả');if(t.status==='working'){assert(state.staff.some(w=>w.id===t.workerId&&w.hired&&!w.former&&w.taskId===t.id),'nhân viên tác vụ không còn hoạt động');if(t.targetId){const key=`${t.type}:${t.targetId}`;assert(!workingTargets.has(key),'hai nhân viên nhận cùng việc');workingTargets.add(key);}}}
 for(const d of state.deliveries)assert(ingredientIds.has(d.ingredient)&&suppliers.some(v=>v.id===d.supplierId)&&integer(d.quantity,1,10000)&&integer(d.unitCost)&&number(d.quality)&&integer(d.remaining,0,200)&&['travel','arrived','quarantined','returned'].includes(d.status),'đơn nhập');
 for(const d of state.deliveries){if(d.expectedQuantity!==undefined)assert(integer(d.expectedQuantity,d.quantity,10000),'số lượng đặt');if(d.discrepancy!==undefined)assert(integer(d.discrepancy,0,10000)&&d.expectedQuantity===d.quantity+d.discrepancy,'chênh lệch giao');if(d.inspected!==undefined)assert(typeof d.inspected==='boolean','kiểm hàng');}
 for(const o of state.orders){if(o.discount!==undefined)assert(integer(o.discount,0,150000),'giảm giá đơn');if(o.lingerUntil!==undefined)assert(integer(o.lingerUntil),'thời gian tại bàn');if(o.serviceAdjustment!==undefined)assert(number(o.serviceAdjustment,-100,100),'điểm phục vụ điều chỉnh');if(o.seatReleased!==undefined)assert(typeof o.seatReleased==='boolean','trạng thái bàn');if(o.draft?.ingredientQuality!==undefined)assert(number(o.draft.ingredientQuality),'chất lượng nguyên liệu món');}
 for(const b of state.baking)assert(integer(b.elapsed)&&integer(b.readyAt,1,180)&&b.burnAt>b.readyAt&&integer(b.cost)&&number(b.decoration)&&['oven','ready','burned','taken'].includes(b.status),'mẻ bánh');
 for(const b of state.baking)if(b.ingredientQuality!==undefined)assert(number(b.ingredientQuality),'chất lượng nguyên liệu bánh');
 for(const c of state.cakes)assert(integer(c.quantity,0,1000)&&number(c.quality)&&integer(c.cost)&&integer(c.expiresDay,1,10050),'kho bánh');
 for(const e of state.equipment)assert(equipmentCatalog.some(a=>a.id===e.id)&&integer(e.level,0,4)&&number(e.durability)&&typeof e.broken==='boolean'&&integer(e.baseCost),'thiết bị');
 const used=new Set<string>();for(const f of state.furniture){const def=furniture.find(a=>a.id===f.kind);assert(def&&integer(f.x,0,15)&&integer(f.y,3,11)&&[0,90,180,270].includes(f.rotation),'nội thất');const w=f.rotation%180?def.height:def.width,h=f.rotation%180?def.width:def.height;for(let y=f.y;y<f.y+h;y++)for(let x=f.x;x<f.x+w;x++){assert(x<16&&y<12&&!(y>=10&&(x===7||x===8)),'đồ chặn cửa / ngoài sàn');assert(def.cat?x>=11:x<11,'khu mèo phải tách khỏi quầy');const key=x+','+y;assert(!used.has(key),'nội thất va chạm');used.add(key);}}
 for(const f of state.storage)assert(furniture.some(a=>a.id===f.kind)&&!state.furniture.some(a=>a.id===f.id),'kho nội thất');
 for(const f of state.furniture)assert(canPlace(state,f.kind,f.x,f.y,f.rotation,f.id).valid,'lối từ cửa đến quầy / khu mèo bị chặn');
 for(const tx of state.transactions){assert(integer(tx.day,1,state.day)&&integer(tx.at,0,state.clock)&&string(tx.label)&&string(tx.category,80),'giao dịch');for(const k of ['cash','revenue','cogs','expense','investment','debt'] as const)assert(integer(tx[k],k==='cogs'?0:-1e9,1e9),'số tiền giao dịch');assert(!tx.orderId||orderIds.has(tx.orderId),'giao dịch không có đơn');if(tx.used)assert(Array.isArray(tx.used)&&tx.used.every(u=>ingredientIds.has(u.ingredient)&&integer(u.quantity)&&integer(u.cost))&&tx.used.reduce((a,b)=>a+b.cost,0)===tx.cogs+Math.max(0,tx.expense),'chi tiết nguyên liệu');if(tx.discount!==undefined)assert(integer(tx.discount,0,100000)&&integer(tx.gross)&&tx.gross-tx.discount===tx.revenue,'giảm giá');}
 assert(state.cash===850000+state.transactions.reduce((a,b)=>a+b.cash,0),'tiền mặt không khớp sổ giao dịch');assert(state.startCash===850000+state.transactions.filter(t=>t.day<state.day).reduce((a,b)=>a+b.cash,0),'tiền đầu ngày không khớp lịch sử');assert(state.reserve===-state.transactions.filter(t=>t.category==='reserve').reduce((a,b)=>a+b.cash,0),'quỹ dự phòng không khớp sổ');
 for(const o of state.orders){const sale=state.transactions.filter(t=>t.id===`sale:${o.id}`);assert(o.paid? sale.length===1:sale.length===0,'thanh toán đơn không khớp sổ');assert(!o.paid||sale[0].revenue===o.price,'giá bán không khớp phiếu');}
 for(const p of state.payables)assert(integer(p.amount)&&integer(p.dueDay,1,10050)&&typeof p.paid==='boolean'&&typeof p.extended==='boolean'&&state.transactions.some(t=>t.id===p.id),'hóa đơn');
 for(const l of state.loans)assert(integer(l.principal,50000,300000)&&integer(l.remaining,0,l.principal)&&number(l.rate,0,.2)&&integer(l.installment,1,l.principal)&&integer(l.nextDay,1,10050)&&state.transactions.some(t=>t.id===l.id&&t.debt===l.principal),'khoản vay');
 for(const l of state.loans){if(l.arrears!==undefined)assert(integer(l.arrears,0,l.remaining)&&l.arrears===state.payables.filter(p=>p.loanId===l.id&&!p.paid).reduce((n,p)=>n+p.amount,0),'gốc quá hạn');}for(const p of state.payables)if(p.loanId)assert(state.loans.some(l=>l.id===p.loanId)&&p.category==='loan-principal','liên kết hóa đơn vay');for(const t of state.transactions){if(t.loanId)assert(state.loans.some(l=>l.id===t.loanId),'liên kết giao dịch vay');if(t.ingredientQuality!==undefined)assert(number(t.ingredientQuality),'chất lượng giao dịch nguyên liệu');}
 assert(Array.isArray(state.collection)&&state.collection.every(n=>string(n,150)),'bộ sưu tập');
 for(const i of state.incidents){assert(['observed','investigating','resolved'].includes(i.stage)&&['light','serious','positive'].includes(i.severity)&&['accident','miscount','misunderstanding','procedure','fraud','theft','positive'].includes(i.cause)&&integer(i.day,1,state.day)&&integer(i.createdAt,0,state.clock)&&string(i.title)&&string(i.description)&&string(i.sign)&&string(i.type,100)&&Array.isArray(i.participants)&&i.participants.every(p=>string(p,180)),'sự cố');assert(Array.isArray(i.evidence)&&i.evidence.length<=10&&i.evidence.every(e=>string(e.id)&&string(e.label)&&string(e.fact)&&number(e.confidence)&&typeof e.checked==='boolean'),'bằng chứng');assert(Array.isArray(i.choices)&&i.choices.length>0&&i.choices.every(c=>string(c.id)&&string(c.label)&&string(c.description)&&integer(c.cost)&&integer(c.duration,1,180)),'lựa chọn sự cố');assert(i.stage!=='resolved'||!i.resolving,'sự cố đã đóng vẫn chạy');assert(integer(i.lossCash)&&integer(i.lossQuantity),'tổn thất');if(i.resolving)assert(i.choices.some(c=>c.id===i.resolving!.choice)&&integer(i.resolving.remaining,0,180),'xử lý sự cố');}
 assert(plain(state.customers)&&Object.keys(state.customers).length===customers.length,'lịch sử khách');for(const c of customers){const h=state.customers[c.id];assert(h&&integer(h.visits)&&number(h.affinity)&&integer(h.loyalty,0,5)&&integer(h.story,0,2),'thiện cảm khách');}
 for(const i of state.incidents){if(i.orderId)assert(orderIds.has(i.orderId),'phiếu liên quan vụ việc');if(i.deliveryId)assert(state.deliveries.some(d=>d.id===i.deliveryId),'lô liên quan vụ việc');if(i.lostFurniture)assert(string(i.lostFurniture.id)&&furniture.some(f=>f.id===i.lostFurniture!.kind)&&integer(i.lostFurniture.x,0,15)&&integer(i.lostFurniture.y,3,11)&&[0,90,180,270].includes(i.lostFurniture.rotation)&&i.furnitureId===i.lostFurniture.id,'đồ mất trong hồ sơ');if(i.furnitureId)assert(state.furniture.some(f=>f.id===i.furnitureId)||state.storage.some(f=>f.id===i.furnitureId)||i.lostFurniture?.id===i.furnitureId,'nội thất liên quan');}
 for(const m of state.missions)assert(integer(m.target,1,100)&&integer(m.progress,0,m.target)&&integer(m.reward)&&typeof m.claimed==='boolean','nhiệm vụ');
 for(const a of state.album)assert(catCatalog.some(c=>c.id===a.catId)&&integer(a.day,1,state.day)&&string(a.caption)&&string(a.pose),'ảnh mèo');
 for(const j of state.journal)assert(integer(j.day,1,state.day)&&integer(j.at,0,state.clock)&&string(j.text)&&['info','event','cat','finance','staff'].includes(j.kind),'nhật ký');
 const reportDays=new Set<number>();for(const r of state.reports){assert(integer(r.day,1,state.day)&&!reportDays.has(r.day),'báo cáo trùng ngày');reportDays.add(r.day);const calculated=reportDay(state,r.day);for(const k of ['revenue','discounts','refunds','netRevenue','cogs','operating','tax','profit','cashFlow','investment','financing'] as const)assert(r[k]===calculated[k],'báo cáo '+k+' không khớp sổ');assert(integer(r.startCash)&&integer(r.endCash)&&r.endCash===r.startCash+r.cashFlow&&r.startCash===850000+state.transactions.filter(t=>t.day<r.day).reduce((a,b)=>a+b.cash,0),'tiền báo cáo');assert(string(r.bestSeller)&&string(r.mostProfitable)&&Array.isArray(r.suggestions)&&r.suggestions.every(t=>string(t))&&Array.isArray(r.waste)&&r.waste.every(w=>ingredientIds.has(w.ingredient as typeof ingredients[number]['id'])&&integer(w.quantity)&&integer(w.cost))&&plain(r.categories)&&Object.values(r.categories).every(n=>integer(n,-1e9,1e9)),'nội dung báo cáo');}
 if(state.day>1)assert(state.reports.some(r=>r.day===state.day-1&&r.endCash===state.startCash),'tiền đầu ngày');
 return state;
}

export function migrateGame(value:unknown):GameState {
 assert(plain(value),'định dạng dữ liệu');const additive={...value,staff:Array.isArray(value.staff)?value.staff.map(w=>plain(w)&&!Object.hasOwn(w,'traits')?{...w,traits:structuredClone(staffCatalog.find(c=>c.id===w.id)?.traits??{})}:w):value.staff};if(value.version===3)return validateGame(additive);
 assert(value.version===1||value.version===2,'phiên bản không được hỗ trợ');
 const base=createGame({seed:typeof value.seed==='number'?value.seed:574823});
 const migrated={...base,...additive,version:3,settings:{...defaultSettings,...(plain(value.settings)?value.settings:{})},reports:Array.isArray(value.reports)?value.reports.map(r=>plain(r)?{discounts:0,...r}:r):base.reports};
 // Version 1/2 snapshots used the same ledger, but lacked accessibility/reserve/insurance fields.
 return validateGame(migrated);
}
export function exportGame(state:GameState):string {validateGame(state);const payload=JSON.stringify(state);return JSON.stringify({format:'miu-matcha',version:3,checksum:checksum(payload),payload:state},null,2);}
export function importGame(text:string):GameState {
 assert(typeof text==='string'&&text.length<=8_000_000,'tệp quá lớn');let parsed:unknown;try{parsed=JSON.parse(text);}catch{throw new Error('Bản lưu không phải JSON hợp lệ.');}
 assert(plain(parsed),'định dạng tệp');if(parsed.format==='miu-matcha'){assert(plain(parsed.payload),'thiếu dữ liệu');assert(parsed.checksum===checksum(JSON.stringify(parsed.payload)),'mã kiểm tra sai hoặc tệp bị hỏng');return migrateGame(parsed.payload);}return migrateGame(parsed);
}
function getDB():Promise<IDBDatabase> {if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return dbPromise;}
async function read(key:string):Promise<string|null>{if(typeof indexedDB==='undefined'){try{return localStorage.getItem(DB_NAME+':'+key);}catch{return memory.get(key)??null;}}const db=await getDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(typeof req.result==='string'?req.result:null);req.onerror=()=>reject(req.error);});}
async function write(entries:[string,string|null][]):Promise<void>{if(typeof indexedDB==='undefined'){for(const [key,value] of entries){try{if(value===null)localStorage.removeItem(DB_NAME+':'+key);else localStorage.setItem(DB_NAME+':'+key,value);}catch{if(value===null)memory.delete(key);else memory.set(key,value);}}return;}const db=await getDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');for(const [key,value] of entries){if(value===null)tx.objectStore(STORE).delete(key);else tx.objectStore(STORE).put(value,key);}tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
let saveQueue:Promise<void>=Promise.resolve();
export async function saveGame(state:GameState):Promise<void> {const serialized=exportGame(state);saveQueue=saveQueue.catch(()=>{}).then(async()=>{const current=await read(CURRENT);let valid=false;if(current)try{importGame(current);valid=true;}catch{/* Keep earlier valid backup. */}await write([[CURRENT,serialized],...(valid?[[BACKUP,current] as [string,string]]:[])]);});return saveQueue;}
export async function loadGame():Promise<GameState|null> {await saveQueue.catch(()=>{});const current=await read(CURRENT);if(current)try{return importGame(current);}catch{/* Try verified backup. */}const backup=await read(BACKUP);if(backup)try{const state=importGame(backup);state.lastMessage='Bản lưu chính bị hỏng; đã phục hồi bản dự phòng hợp lệ.';return state;}catch{/* Both corrupt; preserve files until explicit clear. */}return null;}
export async function clearGame():Promise<void>{await saveQueue.catch(()=>{});await write([[CURRENT,null],[BACKUP,null]]);}
export async function saveSettings(settings:Settings):Promise<void>{await write([[SETTINGS,JSON.stringify(settings)]]);}
export async function loadSettings():Promise<Settings|null>{const raw=await read(SETTINGS);if(!raw)return null;try{const value=JSON.parse(raw);const test=createGame();test.settings=value;validateGame(test);return value;}catch{return null;}}
